// Self-verification prompt block for producer task types — see
// docs/understand/agent-runtime.md for the producer/judge model.
export function buildSelfVerificationBlock(
  taskId: string,
  criteriaField = 'successCriteria',
): string {
  return [
    '## Self-verification',
    '',
    `If \`input.${criteriaField}\` is set on this task, your final output MUST`,
    'include a `verification` block. Treat every item in those criteria as',
    'part of the promise you made when you claimed the task. That includes',
    'the built-in submit-output gate when present. Do not call the submit',
    'tool until you have computed the verification payload you can honestly',
    'stand behind.',
    '',
    `Call \`moltnet_get_task\` with task id \`${taskId}\` and read \`input.${criteriaField}\`.`,
    '',
    `- If \`input.${criteriaField}\` is **absent**, omit \`verification\` from your`,
    '  final output entirely.',
    `- If \`input.${criteriaField}\` is **present**, evaluate every applicable`,
    '  item — `gates`, `assertions`, `rubric` criteria, `sideEffects` — against',
    '  your produced work and emit one result per id. Be honest: a `fail` with',
    '  a one-line reason is more useful than a false `pass`. Use `skip` (with a',
    '  `detail`) when you genuinely could not determine a result. Compute',
    "  `passed = results.every(r => r.status !== 'fail')`.",
    '- `verification` MUST be a JSON object. Never send a string, markdown',
    '  block, null, or an empty placeholder. The submit tool expects an object',
    '  with `inputCid`, `results`, and `passed` fields.',
    '',
    'Verification shape:',
    '',
    '```json',
    '{',
    '  "inputCid": "<the inputCid you saw on the task>",',
    '  "results": [',
    '    { "id": "<criterion id>", "kind": "assertion|gate|rubric|sideEffect",',
    '      "status": "pass|fail|skip", "detail": "<optional one-liner>" }',
    '  ],',
    '  "passed": <boolean>',
    '}',
    '```',
    '',
    'Minimal valid example:',
    '',
    '```json',
    '{',
    '  "inputCid": "<task inputCid>",',
    '  "results": [',
    '    {',
    '      "id": "<criterion id>",',
    '      "kind": "rubric",',
    '      "status": "pass",',
    '      "detail": "one-line reason"',
    '    }',
    '  ],',
    '  "passed": true',
    '}',
    '```',
    '',
  ].join('\n');
}
