// Auto-generated by tools/src/generate-wordmark.ts — do not edit manually.
// Re-run: pnpm generate:wordmark
export const WORDMARK =
  '    __  _______  __  _______   ______________\n   /  |/  / __ \\/ / /_  __/ | / / ____/_  __/\n  / /|_/ / / / / /   / / /  |/ / __/   / /   \n / /  / / /_/ / /___/ / / /|  / /___  / /    \n/_/  /_/\\____/_____/_/ /_/ |_/_____/ /_/';
