packages:
  - 'apps/*'
  - 'libs/*'

catalog:
  # TypeScript & build tooling
  typescript: ^5.3.3
  tsx: ^4.7.0
  vite: ^6.0.0
  '@vitejs/plugin-react': ^4.3.0

  # Testing
  vitest: ^3.0.0

  # Linting & formatting
  eslint: ^9.0.0
  '@eslint/js': ^9.0.0
  typescript-eslint: ^8.0.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-react-hooks: ^7.0.1
  prettier: ^3.2.4

  # Type definitions
  '@types/node': ^20.11.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0

  # Code analysis
  knip: ^5.82.1

  # Git hooks & secrets
  husky: ^9.1.0
  lint-staged: ^15.2.0
  '@dotenvx/dotenvx': ^1.52.0

  # React
  react: ^19.0.0
  react-dom: ^19.0.0

  # Fastify
  fastify: ^5.2.0
  fastify-plugin: ^5.0.0
  '@fastify/otel': ^0.16.0

  # Database
  drizzle-orm: ^0.29.3
  drizzle-kit: ^0.20.13
  postgres: ^3.4.3

  # Crypto
  '@noble/ed25519': ^2.0.0

  # Validation
  '@sinclair/typebox': ^0.32.9

  # Observability - OpenTelemetry
  '@opentelemetry/api': ^1.7.0
  '@opentelemetry/sdk-trace-base': ^1.30.0
  '@opentelemetry/sdk-trace-node': ^1.30.0
  '@opentelemetry/sdk-metrics': ^1.30.0
  '@opentelemetry/resources': ^1.30.0
  '@opentelemetry/semantic-conventions': ^1.28.0
  '@opentelemetry/exporter-trace-otlp-proto': ^0.57.0
  '@opentelemetry/exporter-metrics-otlp-proto': ^0.57.0

  # Observability - Logging
  pino: ^9.6.0
  pino-pretty: ^13.0.0
  pino-opentelemetry-transport: ^0.6.0

  # Auth (Ory)
  '@ory/client': ^1.22.0

  # API
  '@fastify/swagger': ^9.6.1

  # MCP
  '@modelcontextprotocol/sdk': ^1.25.0
  zod: ^3.25.0

  # Embeddings
  '@huggingface/transformers': ^3.4.0

  # API Client generation
  '@hey-api/client-fetch': 0.9.0
  '@hey-api/openapi-ts': 0.89.2
