packages:
  - apps/*
  - libs/*
  - tools

catalog:
  '@dbos-inc/dbos-sdk': ^4.8.0
  '@dbos-inc/drizzle-datasource': ^4.8.0
  '@dotenvx/dotenvx': ^1.52.0
  '@eslint/js': ^9.0.0
  '@fastify/cors': ^11.0.0
  '@fastify/helmet': ^13.0.1
  '@fastify/otel': ^0.16.0
  '@fastify/rate-limit': ^10.2.1
  '@fastify/static': ^9.0.0
  '@fastify/swagger': ^9.6.1
  '@fastify/type-provider-typebox': ^5.2.0
  '@hey-api/client-fetch': 0.9.0
  '@hey-api/openapi-ts': 0.89.2
  '@huggingface/transformers': ^3.4.0
  '@modelcontextprotocol/sdk': ^1.26.0
  '@noble/ed25519': ^2.0.0
  '@opentelemetry/api': ^1.7.0
  '@opentelemetry/exporter-logs-otlp-proto': ^0.57.0
  '@opentelemetry/exporter-metrics-otlp-proto': ^0.57.0
  '@opentelemetry/exporter-trace-otlp-proto': ^0.57.0
  '@opentelemetry/resources': ^1.30.0
  '@opentelemetry/sdk-metrics': ^1.30.0
  '@opentelemetry/sdk-trace-base': ^1.30.0
  '@opentelemetry/sdk-trace-node': ^1.30.0
  '@opentelemetry/semantic-conventions': ^1.28.0
  '@ory/client-fetch': ^1.22.0
  '@getlarge/fastify-mcp': ^1.3.0-getlarge.1
  '@sinclair/typebox': ^0.34.0
  '@types/node': ^20.11.0
  '@types/pg': ^8.11.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@vitejs/plugin-react': ^4.3.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.0.0
  eslint-plugin-boundaries: ^5.4.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-simple-import-sort: ^12.1.1
  fast-jwt: ^5.0.0
  fastify: ^5.7.3
  fastify-plugin: ^5.1.0
  get-jwks: ^11.0.2
  husky: ^9.1.0
  knip: ^5.82.1
  lint-staged: ^15.2.0
  pg: ^8.13.0
  pino: ^9.6.0
  pino-opentelemetry-transport: ^0.6.0
  pino-pretty: ^13.0.0
  prettier: ^3.2.4
  react: ^19.0.0
  smol-toml: ^1.6.0
  react-dom: ^19.0.0
  thread-stream: ^3.1.0
  tsx: ^4.7.0
  typescript: ^5.3.3
  typescript-eslint: ^8.0.0
  update-ts-references: ^4.0.0
  vite: ^6.0.0
  vitest: ^3.0.0
  winston: 3.17.0
  winston-transport: 4.7.0
  wouter: ^3.7.0
  zod: ^3.25.0
