version: v2.3.0

serve:
  public:
    cors:
      enabled: true
      allowed_origins:
        - https://${CONSOLE_DOMAIN}
        - https://${API_DOMAIN}
      allow_credentials: true

urls:
  self:
    issuer: https://${OAUTH_DOMAIN}/
    public: https://${OAUTH_DOMAIN}/
  consent: https://${IDENTITY_DOMAIN}/consent
  login: https://${IDENTITY_DOMAIN}/login
  logout: https://${IDENTITY_DOMAIN}/logout
  error: https://${CONSOLE_DOMAIN}/auth/error
  post_logout_redirect: https://${CONSOLE_DOMAIN}/

strategies:
  access_token: jwt

oauth2:
  grant:
    jwt:
      iat_optional: false
      jti_optional: false
      max_ttl: 720h
  client_credentials:
    default_grant_allowed_scope: true
  session:
    encrypt_at_rest: true
  pkce:
    enforced: false
    enforced_for_public_clients: true
  token_hook:
    url: http://rest-api:8080/hooks/hydra/token-exchange
    auth:
      type: api_key
      config:
        in: header
        name: X-Ory-Api-Key
        value: ${ORY_ACTION_API_KEY}

webfinger:
  oidc_discovery:
    token_url: https://${API_DOMAIN}/oauth2/token
    client_registration_url: https://${OAUTH_DOMAIN}/oauth2/register

oidc:
  subject_identifiers:
    supported_types: [public]
  dynamic_client_registration:
    enabled: true
    default_scope:
      - agent:profile
      - connector:invoke
      - crypto:sign
      - diary:manage
      - diary:read
      - diary:write
      - key:manage
      - pack:read
      - pack:write
      - runtime:manage
      - runtime:read
      - task:claim
      - task:execute
      - task:manage
      - task:read
      - team:manage
      - team:read

ttl:
  access_token: 24h
  refresh_token: 720h
  id_token: 1h
  auth_code: 10m
  login_consent_request: 30m
