/**
 * Runtime locks for GitHub Actions released by release-please.
 *
 * release-please bumps a component only for commits under its package path,
 * but consumers pinned to `docs-impact-review-action-v0` also run the
 * reusable workflow and the agent-daemon action at that tag's commit. The
 * lock file inside the package records a hash of each of those files, so a
 * change to one must update the lock, which touches the package and cuts a
 * release.
 *
 * Plain Node (erasable TypeScript, built-ins only), so CI runs it without an
 * install: `node tools/src/release/action-runtime-lock.ts --check|--write`.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export interface RuntimeLock {
  /** Lock file, relative to the repository root. */
  lock: string;
  /** Git pathspecs of the files the action runs from outside its package. */
  pathspecs: string[];
}

export const RUNTIME_LOCKS: RuntimeLock[] = [
  {
    lock: 'packages/complexity-review-action/runtime.lock',
    pathspecs: [
      '.github/workflows/complexity-review-reusable.yml',
      'packages/agent-daemon-action/action.yml',
      'packages/agent-daemon-action/dist',
    ],
  },
  {
    lock: 'packages/docs-impact-review-action/runtime.lock',
    pathspecs: [
      '.github/workflows/docs-impact-review-reusable.yml',
      'packages/agent-daemon-action/action.yml',
      // The bundle the workers run, not its sources: the bundle-sync PR
      // refreshes this lock together with the bundle.
      'packages/agent-daemon-action/dist',
    ],
  },
];

const HEADER = [
  '# Generated by tools/src/release/action-runtime-lock.ts --write.',
  '# Files this action runs from outside its package; a change here must',
  '# ship as a fix or feat commit so release-please releases the action.',
];

/** The lock text for `files` (path → content), sorted by path. */
export function renderLock(files: ReadonlyMap<string, Buffer>): string {
  const lines = [...files.keys()].sort().map((path) => {
    const content = files.get(path) ?? Buffer.alloc(0);
    return `${createHash('sha256').update(content).digest('hex')}  ${path}`;
  });
  return `${[...HEADER, ...lines].join('\n')}\n`;
}

function listFiles(root: string, pathspecs: string[]): string[] {
  return execFileSync(
    'git',
    // Staged files only, NUL-separated: an untracked local file never enters
    // the lock, and no path is quoted.
    ['ls-files', '--cached', '-z', '--', ...pathspecs],
    { cwd: root, encoding: 'utf8' },
  )
    .split('\0')
    .filter(Boolean);
}

export function computeLock(root: string, spec: RuntimeLock): string {
  const files = new Map<string, Buffer>();
  for (const path of listFiles(root, spec.pathspecs)) {
    files.set(path, readFileSync(join(root, path)));
  }
  return renderLock(files);
}

/** Locks whose committed text differs from the files they cover. */
export function staleLocks(root: string, locks = RUNTIME_LOCKS): string[] {
  return locks
    .filter((spec) => {
      let current = '';
      try {
        current = readFileSync(join(root, spec.lock), 'utf8');
      } catch {
        return true;
      }
      return current !== computeLock(root, spec);
    })
    .map((spec) => spec.lock);
}

function main(argv: string[]): number {
  const root = execFileSync('git', ['rev-parse', '--show-toplevel'], {
    encoding: 'utf8',
  }).trim();
  if (argv.includes('--write')) {
    for (const spec of RUNTIME_LOCKS) {
      writeFileSync(join(root, spec.lock), computeLock(root, spec));
    }
    return 0;
  }
  if (argv.includes('--check')) {
    const stale = staleLocks(root);
    for (const lock of stale) {
      process.stderr.write(
        `::error file=${lock}::${lock} is out of date. Stage your changes, run 'node tools/src/release/action-runtime-lock.ts --write', and commit the lock in a fix or feat commit, so the action is released with the change.\n`,
      );
    }
    return stale.length > 0 ? 1 : 0;
  }
  process.stderr.write(
    'Usage: node tools/src/release/action-runtime-lock.ts --check|--write\n',
  );
  return 2;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  process.exitCode = main(process.argv.slice(2));
}
