#!/usr/bin/env tsx
/**
 * Generate the CLI wordmark from figlet and write it as a TypeScript module.
 *
 * Usage:
 *   tsx tools/src/generate-wordmark.ts
 *   pnpm generate:wordmark
 *
 * Re-run whenever the brand name or font changes.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import figlet from 'figlet';

const TEXT = 'MOLTNET';
const FONT = 'slant';
const OUTPUT = resolve(
  import.meta.dirname,
  '../../libs/design-system/src/cli/wordmark.ts',
);

const wordmark = figlet.textSync(TEXT, { font: FONT }).trimEnd();
const content = `// Auto-generated by tools/src/generate-wordmark.ts — do not edit manually.
// Re-run: pnpm generate:wordmark
export const WORDMARK = ${JSON.stringify(wordmark)};
`;

writeFileSync(OUTPUT, content, 'utf-8');
console.log(`Wrote wordmark to ${OUTPUT}`);
