// Generated from Pi by the provider-catalog generator.
// Do not edit manually.
import type { RuntimeModelCatalogEntry } from './types.js';

export const piRuntimeModels: readonly RuntimeModelCatalogEntry[] = [
  {
    provider: 'anthropic',
    model: 'claude-fable-5',
    displayName: 'Anthropic · Claude Fable 5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-fable-5-1',
    displayName: 'Anthropic · Claude Fable 5.1',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku-4-5',
    displayName: 'Anthropic · Claude Haiku 4.5 (latest)',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 200000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    displayName: 'Anthropic · Claude Haiku 4.5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 200000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-5',
    displayName: 'Anthropic · Claude Opus 4.5 (latest)',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 200000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-5-20251101',
    displayName: 'Anthropic · Claude Opus 4.5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 200000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-6',
    displayName: 'Anthropic · Claude Opus 4.6',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-7',
    displayName: 'Anthropic · Claude Opus 4.7',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    displayName: 'Anthropic · Claude Opus 4.8',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-5',
    displayName: 'Anthropic · Claude Opus 5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-5-5',
    displayName: 'Anthropic · Claude Opus 5.5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-5',
    displayName: 'Anthropic · Claude Sonnet 4.5 (latest)',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-5-20250929',
    displayName: 'Anthropic · Claude Sonnet 4.5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 64000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    displayName: 'Anthropic · Claude Sonnet 4.6',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    displayName: 'Anthropic · Claude Sonnet 5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: true,
      supportsTopP: true,
      supportsTopK: true,
      supportsMaxOutputTokens: true,
      contextWindow: 1000000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-5.3-codex-spark',
    displayName: 'OpenAI Codex · GPT-5.3 Codex Spark',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: false,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 128000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-5.5',
    displayName: 'OpenAI Codex · GPT-5.5',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-5.6-luna',
    displayName: 'OpenAI Codex · GPT-5.6 Luna',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-5.6-sol',
    displayName: 'OpenAI Codex · GPT-5.6 Sol',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-5.6-terra',
    displayName: 'OpenAI Codex · GPT-5.6 Terra',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-6-astra',
    displayName: 'OpenAI Codex · GPT-6 Astra',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-6-luna',
    displayName: 'OpenAI Codex · GPT-6 Luna',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
  {
    provider: 'openai-codex',
    model: 'gpt-6-sol',
    displayName: 'OpenAI Codex · GPT-6 Sol',
    description: 'Generated from Pi static provider catalog.',
    capabilities: {
      supportsReasoning: true,
      supportsVision: true,
      supportsTemperature: false,
      supportsTopP: false,
      supportsTopK: false,
      supportsMaxOutputTokens: false,
      contextWindow: 272000,
      maxOutputTokens: 128000,
    },
  },
];
