export {
  AGENT_CREDENTIAL_SCOPES,
  AGENT_OAUTH_SCOPES,
  ALL_CREDENTIAL_SCOPES,
  CREDENTIAL_SCOPES,
  type CredentialScope,
  credentialScopeSetsEqual,
  HUMAN_SESSION_SCOPES,
  MCP_CLIENT_SCOPES,
  TEAM_AGENT_KEY_SCOPES,
} from '@moltnet/models';
