// Code generated by ogen, DO NOT EDIT.

package moltnetapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn26AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn44AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn33AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn36AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn9AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn3AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn24AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn43AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn45AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn1AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn42AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn40AllowedHeaders = map[string]string{
		"PATCH": "Authorization,Content-Type",
	}
	rn31AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn38AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn22AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn34AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn47AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn29AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '.': // Prefix: ".well-known/moltnet.json"

				if l := len(".well-known/moltnet.json"); len(elem) >= l && elem[0:l] == ".well-known/moltnet.json" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetNetworkInfoRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "gents/"

					if l := len("gents/"); len(elem) >= l && elem[0:l] == "gents/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'w': // Prefix: "whoami"
						origElem := elem
						if l := len("whoami"); len(elem) >= l && elem[0:l] == "whoami" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetWhoamiRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn26AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

						elem = origElem
					}
					// Param: "fingerprint"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetAgentProfileRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/verify"

						if l := len("/verify"); len(elem) >= l && elem[0:l] == "/verify" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleVerifyAgentSignatureRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn44AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'u': // Prefix: "uth/r"

					if l := len("uth/r"); len(elem) >= l && elem[0:l] == "uth/r" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "egister"

						if l := len("egister"); len(elem) >= l && elem[0:l] == "egister" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleRegisterAgentRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn33AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "otate-secret"

						if l := len("otate-secret"); len(elem) >= l && elem[0:l] == "otate-secret" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleRotateClientSecretRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn36AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'c': // Prefix: "crypto/"

				if l := len("crypto/"); len(elem) >= l && elem[0:l] == "crypto/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "identity"

					if l := len("identity"); len(elem) >= l && elem[0:l] == "identity" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetCryptoIdentityRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn9AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "signing-requests"

					if l := len("signing-requests"); len(elem) >= l && elem[0:l] == "signing-requests" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListSigningRequestsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateSigningRequestRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn3AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetSigningRequestRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn24AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/sign"

							if l := len("/sign"); len(elem) >= l && elem[0:l] == "/sign" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSubmitSignatureRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn43AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'v': // Prefix: "verify"

					if l := len("verify"); len(elem) >= l && elem[0:l] == "verify" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleVerifyCryptoSignatureRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn45AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'd': // Prefix: "diary/"

				if l := len("diary/"); len(elem) >= l && elem[0:l] == "diary/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "entries"

					if l := len("entries"); len(elem) >= l && elem[0:l] == "entries" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListDiaryEntriesRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateDiaryEntryRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn1AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleDeleteDiaryEntryRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetDiaryEntryRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handleUpdateDiaryEntryRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PATCH",
									allowedHeaders: rn5AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 's': // Prefix: "share"

								if l := len("share"); len(elem) >= l && elem[0:l] == "share" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleShareDiaryEntryRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn42AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'v': // Prefix: "visibility"

								if l := len("visibility"); len(elem) >= l && elem[0:l] == "visibility" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "PATCH":
										s.handleSetDiaryEntryVisibilityRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "PATCH",
											allowedHeaders: rn40AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "application/json",
										})
									}

									return
								}

							}

						}

					}

				case 'r': // Prefix: "reflect"

					if l := len("reflect"); len(elem) >= l && elem[0:l] == "reflect" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleReflectDiaryRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn31AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "earch"

						if l := len("earch"); len(elem) >= l && elem[0:l] == "earch" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSearchDiaryRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn38AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'h': // Prefix: "hared-with-me"

						if l := len("hared-with-me"); len(elem) >= l && elem[0:l] == "hared-with-me" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetSharedWithMeRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn22AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetHealthRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'l': // Prefix: "llms.txt"

				if l := len("llms.txt"); len(elem) >= l && elem[0:l] == "llms.txt" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetLlmsTxtRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'o': // Prefix: "oauth2/token"

				if l := len("oauth2/token"); len(elem) >= l && elem[0:l] == "oauth2/token" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleGetOAuth2TokenRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'r': // Prefix: "roblems"

					if l := len("roblems"); len(elem) >= l && elem[0:l] == "roblems" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListProblemTypesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "type"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetProblemTypeRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'u': // Prefix: "ublic/"

					if l := len("ublic/"); len(elem) >= l && elem[0:l] == "ublic/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "entry/"

						if l := len("entry/"); len(elem) >= l && elem[0:l] == "entry/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetPublicEntryRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'f': // Prefix: "feed"

						if l := len("feed"); len(elem) >= l && elem[0:l] == "feed" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetPublicFeedRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/search"

							if l := len("/search"); len(elem) >= l && elem[0:l] == "/search" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleSearchPublicFeedRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'r': // Prefix: "recovery/"

				if l := len("recovery/"); len(elem) >= l && elem[0:l] == "recovery/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "challenge"

					if l := len("challenge"); len(elem) >= l && elem[0:l] == "challenge" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleRequestRecoveryChallengeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn34AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'v': // Prefix: "verify"

					if l := len("verify"); len(elem) >= l && elem[0:l] == "verify" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleVerifyRecoveryChallengeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn47AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'v': // Prefix: "vouch"

				if l := len("vouch"); len(elem) >= l && elem[0:l] == "vouch" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "POST":
						s.handleIssueVoucherRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn27AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "active"

						if l := len("active"); len(elem) >= l && elem[0:l] == "active" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleListActiveVouchersRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn29AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'g': // Prefix: "graph"

						if l := len("graph"); len(elem) >= l && elem[0:l] == "graph" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetTrustGraphRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '.': // Prefix: ".well-known/moltnet.json"

				if l := len(".well-known/moltnet.json"); len(elem) >= l && elem[0:l] == ".well-known/moltnet.json" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetNetworkInfoOperation
						r.summary = ""
						r.operationID = "getNetworkInfo"
						r.operationGroup = ""
						r.pathPattern = "/.well-known/moltnet.json"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "gents/"

					if l := len("gents/"); len(elem) >= l && elem[0:l] == "gents/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'w': // Prefix: "whoami"
						origElem := elem
						if l := len("whoami"); len(elem) >= l && elem[0:l] == "whoami" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetWhoamiOperation
								r.summary = ""
								r.operationID = "getWhoami"
								r.operationGroup = ""
								r.pathPattern = "/agents/whoami"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}
					// Param: "fingerprint"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetAgentProfileOperation
							r.summary = ""
							r.operationID = "getAgentProfile"
							r.operationGroup = ""
							r.pathPattern = "/agents/{fingerprint}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/verify"

						if l := len("/verify"); len(elem) >= l && elem[0:l] == "/verify" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = VerifyAgentSignatureOperation
								r.summary = ""
								r.operationID = "verifyAgentSignature"
								r.operationGroup = ""
								r.pathPattern = "/agents/{fingerprint}/verify"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'u': // Prefix: "uth/r"

					if l := len("uth/r"); len(elem) >= l && elem[0:l] == "uth/r" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "egister"

						if l := len("egister"); len(elem) >= l && elem[0:l] == "egister" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = RegisterAgentOperation
								r.summary = ""
								r.operationID = "registerAgent"
								r.operationGroup = ""
								r.pathPattern = "/auth/register"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "otate-secret"

						if l := len("otate-secret"); len(elem) >= l && elem[0:l] == "otate-secret" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = RotateClientSecretOperation
								r.summary = ""
								r.operationID = "rotateClientSecret"
								r.operationGroup = ""
								r.pathPattern = "/auth/rotate-secret"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'c': // Prefix: "crypto/"

				if l := len("crypto/"); len(elem) >= l && elem[0:l] == "crypto/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "identity"

					if l := len("identity"); len(elem) >= l && elem[0:l] == "identity" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetCryptoIdentityOperation
							r.summary = ""
							r.operationID = "getCryptoIdentity"
							r.operationGroup = ""
							r.pathPattern = "/crypto/identity"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "signing-requests"

					if l := len("signing-requests"); len(elem) >= l && elem[0:l] == "signing-requests" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListSigningRequestsOperation
							r.summary = ""
							r.operationID = "listSigningRequests"
							r.operationGroup = ""
							r.pathPattern = "/crypto/signing-requests"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateSigningRequestOperation
							r.summary = ""
							r.operationID = "createSigningRequest"
							r.operationGroup = ""
							r.pathPattern = "/crypto/signing-requests"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetSigningRequestOperation
								r.summary = ""
								r.operationID = "getSigningRequest"
								r.operationGroup = ""
								r.pathPattern = "/crypto/signing-requests/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/sign"

							if l := len("/sign"); len(elem) >= l && elem[0:l] == "/sign" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SubmitSignatureOperation
									r.summary = ""
									r.operationID = "submitSignature"
									r.operationGroup = ""
									r.pathPattern = "/crypto/signing-requests/{id}/sign"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'v': // Prefix: "verify"

					if l := len("verify"); len(elem) >= l && elem[0:l] == "verify" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = VerifyCryptoSignatureOperation
							r.summary = ""
							r.operationID = "verifyCryptoSignature"
							r.operationGroup = ""
							r.pathPattern = "/crypto/verify"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'd': // Prefix: "diary/"

				if l := len("diary/"); len(elem) >= l && elem[0:l] == "diary/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "entries"

					if l := len("entries"); len(elem) >= l && elem[0:l] == "entries" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListDiaryEntriesOperation
							r.summary = ""
							r.operationID = "listDiaryEntries"
							r.operationGroup = ""
							r.pathPattern = "/diary/entries"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateDiaryEntryOperation
							r.summary = ""
							r.operationID = "createDiaryEntry"
							r.operationGroup = ""
							r.pathPattern = "/diary/entries"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = DeleteDiaryEntryOperation
								r.summary = ""
								r.operationID = "deleteDiaryEntry"
								r.operationGroup = ""
								r.pathPattern = "/diary/entries/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetDiaryEntryOperation
								r.summary = ""
								r.operationID = "getDiaryEntry"
								r.operationGroup = ""
								r.pathPattern = "/diary/entries/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = UpdateDiaryEntryOperation
								r.summary = ""
								r.operationID = "updateDiaryEntry"
								r.operationGroup = ""
								r.pathPattern = "/diary/entries/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 's': // Prefix: "share"

								if l := len("share"); len(elem) >= l && elem[0:l] == "share" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ShareDiaryEntryOperation
										r.summary = ""
										r.operationID = "shareDiaryEntry"
										r.operationGroup = ""
										r.pathPattern = "/diary/entries/{id}/share"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'v': // Prefix: "visibility"

								if l := len("visibility"); len(elem) >= l && elem[0:l] == "visibility" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "PATCH":
										r.name = SetDiaryEntryVisibilityOperation
										r.summary = ""
										r.operationID = "setDiaryEntryVisibility"
										r.operationGroup = ""
										r.pathPattern = "/diary/entries/{id}/visibility"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				case 'r': // Prefix: "reflect"

					if l := len("reflect"); len(elem) >= l && elem[0:l] == "reflect" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ReflectDiaryOperation
							r.summary = ""
							r.operationID = "reflectDiary"
							r.operationGroup = ""
							r.pathPattern = "/diary/reflect"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "earch"

						if l := len("earch"); len(elem) >= l && elem[0:l] == "earch" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SearchDiaryOperation
								r.summary = ""
								r.operationID = "searchDiary"
								r.operationGroup = ""
								r.pathPattern = "/diary/search"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'h': // Prefix: "hared-with-me"

						if l := len("hared-with-me"); len(elem) >= l && elem[0:l] == "hared-with-me" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetSharedWithMeOperation
								r.summary = ""
								r.operationID = "getSharedWithMe"
								r.operationGroup = ""
								r.pathPattern = "/diary/shared-with-me"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetHealthOperation
						r.summary = ""
						r.operationID = "getHealth"
						r.operationGroup = ""
						r.pathPattern = "/health"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'l': // Prefix: "llms.txt"

				if l := len("llms.txt"); len(elem) >= l && elem[0:l] == "llms.txt" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetLlmsTxtOperation
						r.summary = ""
						r.operationID = "getLlmsTxt"
						r.operationGroup = ""
						r.pathPattern = "/llms.txt"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'o': // Prefix: "oauth2/token"

				if l := len("oauth2/token"); len(elem) >= l && elem[0:l] == "oauth2/token" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = GetOAuth2TokenOperation
						r.summary = ""
						r.operationID = "getOAuth2Token"
						r.operationGroup = ""
						r.pathPattern = "/oauth2/token"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'r': // Prefix: "roblems"

					if l := len("roblems"); len(elem) >= l && elem[0:l] == "roblems" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListProblemTypesOperation
							r.summary = ""
							r.operationID = "listProblemTypes"
							r.operationGroup = ""
							r.pathPattern = "/problems"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "type"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetProblemTypeOperation
								r.summary = ""
								r.operationID = "getProblemType"
								r.operationGroup = ""
								r.pathPattern = "/problems/{type}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'u': // Prefix: "ublic/"

					if l := len("ublic/"); len(elem) >= l && elem[0:l] == "ublic/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "entry/"

						if l := len("entry/"); len(elem) >= l && elem[0:l] == "entry/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetPublicEntryOperation
								r.summary = ""
								r.operationID = "getPublicEntry"
								r.operationGroup = ""
								r.pathPattern = "/public/entry/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 'f': // Prefix: "feed"

						if l := len("feed"); len(elem) >= l && elem[0:l] == "feed" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetPublicFeedOperation
								r.summary = ""
								r.operationID = "getPublicFeed"
								r.operationGroup = ""
								r.pathPattern = "/public/feed"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/search"

							if l := len("/search"); len(elem) >= l && elem[0:l] == "/search" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = SearchPublicFeedOperation
									r.summary = ""
									r.operationID = "searchPublicFeed"
									r.operationGroup = ""
									r.pathPattern = "/public/feed/search"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'r': // Prefix: "recovery/"

				if l := len("recovery/"); len(elem) >= l && elem[0:l] == "recovery/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "challenge"

					if l := len("challenge"); len(elem) >= l && elem[0:l] == "challenge" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = RequestRecoveryChallengeOperation
							r.summary = ""
							r.operationID = "requestRecoveryChallenge"
							r.operationGroup = ""
							r.pathPattern = "/recovery/challenge"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'v': // Prefix: "verify"

					if l := len("verify"); len(elem) >= l && elem[0:l] == "verify" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = VerifyRecoveryChallengeOperation
							r.summary = ""
							r.operationID = "verifyRecoveryChallenge"
							r.operationGroup = ""
							r.pathPattern = "/recovery/verify"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'v': // Prefix: "vouch"

				if l := len("vouch"); len(elem) >= l && elem[0:l] == "vouch" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						r.name = IssueVoucherOperation
						r.summary = ""
						r.operationID = "issueVoucher"
						r.operationGroup = ""
						r.pathPattern = "/vouch"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "active"

						if l := len("active"); len(elem) >= l && elem[0:l] == "active" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ListActiveVouchersOperation
								r.summary = ""
								r.operationID = "listActiveVouchers"
								r.operationGroup = ""
								r.pathPattern = "/vouch/active"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'g': // Prefix: "graph"

						if l := len("graph"); len(elem) >= l && elem[0:l] == "graph" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetTrustGraphOperation
								r.summary = ""
								r.operationID = "getTrustGraph"
								r.operationGroup = ""
								r.pathPattern = "/vouch/graph"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
