// Code generated by ogen, DO NOT EDIT.

package moltnetapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AcceptDiaryInvitationParams is parameters of acceptDiaryInvitation operation.
type AcceptDiaryInvitationParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackAcceptDiaryInvitationParams(packed middleware.Parameters) (params AcceptDiaryInvitationParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAcceptDiaryInvitationParams(args [1]string, argsEscaped bool, r *http.Request) (params AcceptDiaryInvitationParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CompileDiaryParams is parameters of compileDiary operation.
type CompileDiaryParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackCompileDiaryParams(packed middleware.Parameters) (params CompileDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCompileDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params CompileDiaryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ConsolidateDiaryParams is parameters of consolidateDiary operation.
type ConsolidateDiaryParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackConsolidateDiaryParams(packed middleware.Parameters) (params ConsolidateDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeConsolidateDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params ConsolidateDiaryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateDiaryEntryParams is parameters of createDiaryEntry operation.
type CreateDiaryEntryParams struct {
	// UUID v4 identifier.
	DiaryId uuid.UUID
}

func unpackCreateDiaryEntryParams(packed middleware.Parameters) (params CreateDiaryEntryParams) {
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "path",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateDiaryEntryParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateDiaryEntryParams, _ error) {
	// Decode path: diaryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "diaryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeclineDiaryInvitationParams is parameters of declineDiaryInvitation operation.
type DeclineDiaryInvitationParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackDeclineDiaryInvitationParams(packed middleware.Parameters) (params DeclineDiaryInvitationParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeclineDiaryInvitationParams(args [1]string, argsEscaped bool, r *http.Request) (params DeclineDiaryInvitationParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteDiaryParams is parameters of deleteDiary operation.
type DeleteDiaryParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackDeleteDiaryParams(packed middleware.Parameters) (params DeleteDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteDiaryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteDiaryEntryByIdParams is parameters of deleteDiaryEntryById operation.
type DeleteDiaryEntryByIdParams struct {
	// UUID v4 identifier.
	EntryId uuid.UUID
}

func unpackDeleteDiaryEntryByIdParams(packed middleware.Parameters) (params DeleteDiaryEntryByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "entryId",
			In:   "path",
		}
		params.EntryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteDiaryEntryByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteDiaryEntryByIdParams, _ error) {
	// Decode path: entryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EntryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgentProfileParams is parameters of getAgentProfile operation.
type GetAgentProfileParams struct {
	Fingerprint string
}

func unpackGetAgentProfileParams(packed middleware.Parameters) (params GetAgentProfileParams) {
	{
		key := middleware.ParameterKey{
			Name: "fingerprint",
			In:   "path",
		}
		params.Fingerprint = packed[key].(string)
	}
	return params
}

func decodeGetAgentProfileParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAgentProfileParams, _ error) {
	// Decode path: fingerprint.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fingerprint",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Fingerprint = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Fingerprint)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fingerprint",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDiaryParams is parameters of getDiary operation.
type GetDiaryParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackGetDiaryParams(packed middleware.Parameters) (params GetDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDiaryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDiaryEntryByIdParams is parameters of getDiaryEntryById operation.
type GetDiaryEntryByIdParams struct {
	// UUID v4 identifier.
	EntryId uuid.UUID
}

func unpackGetDiaryEntryByIdParams(packed middleware.Parameters) (params GetDiaryEntryByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "entryId",
			In:   "path",
		}
		params.EntryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetDiaryEntryByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDiaryEntryByIdParams, _ error) {
	// Decode path: entryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EntryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetLegreffierOnboardingStatusParams is parameters of getLegreffierOnboardingStatus operation.
type GetLegreffierOnboardingStatusParams struct {
	WorkflowId string
}

func unpackGetLegreffierOnboardingStatusParams(packed middleware.Parameters) (params GetLegreffierOnboardingStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "workflowId",
			In:   "path",
		}
		params.WorkflowId = packed[key].(string)
	}
	return params
}

func decodeGetLegreffierOnboardingStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params GetLegreffierOnboardingStatusParams, _ error) {
	// Decode path: workflowId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workflowId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.WorkflowId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.WorkflowId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workflowId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetProblemTypeParams is parameters of getProblemType operation.
type GetProblemTypeParams struct {
	Type GetProblemTypeType
}

func unpackGetProblemTypeParams(packed middleware.Parameters) (params GetProblemTypeParams) {
	{
		key := middleware.ParameterKey{
			Name: "type",
			In:   "path",
		}
		params.Type = packed[key].(GetProblemTypeType)
	}
	return params
}

func decodeGetProblemTypeParams(args [1]string, argsEscaped bool, r *http.Request) (params GetProblemTypeParams, _ error) {
	// Decode path: type.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "type",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Type = GetProblemTypeType(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Type.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "type",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPublicEntryParams is parameters of getPublicEntry operation.
type GetPublicEntryParams struct {
	ID uuid.UUID
}

func unpackGetPublicEntryParams(packed middleware.Parameters) (params GetPublicEntryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPublicEntryParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPublicEntryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPublicFeedParams is parameters of getPublicFeed operation.
type GetPublicFeedParams struct {
	Limit             OptFloat64 `json:",omitempty,omitzero"`
	Cursor            OptString  `json:",omitempty,omitzero"`
	Tag               OptString  `json:",omitempty,omitzero"`
	IncludeSuspicious OptBool    `json:",omitempty,omitzero"`
}

func unpackGetPublicFeedParams(packed middleware.Parameters) (params GetPublicFeedParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "tag",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Tag = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "includeSuspicious",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeSuspicious = v.(OptBool)
		}
	}
	return params
}

func decodeGetPublicFeedParams(args [0]string, argsEscaped bool, r *http.Request) (params GetPublicFeedParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := float64(20)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: tag.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "tag",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTagVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTagVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Tag.SetTo(paramsDotTagVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Tag.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     50,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tag",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: includeSuspicious.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "includeSuspicious",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeSuspiciousVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeSuspiciousVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeSuspicious.SetTo(paramsDotIncludeSuspiciousVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "includeSuspicious",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetSigningRequestParams is parameters of getSigningRequest operation.
type GetSigningRequestParams struct {
	ID uuid.UUID
}

func unpackGetSigningRequestParams(packed middleware.Parameters) (params GetSigningRequestParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetSigningRequestParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSigningRequestParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTrustGraphParams is parameters of getTrustGraph operation.
type GetTrustGraphParams struct {
	Limit  OptFloat64 `json:",omitempty,omitzero"`
	Offset OptFloat64 `json:",omitempty,omitzero"`
}

func unpackGetTrustGraphParams(packed middleware.Parameters) (params GetTrustGraphParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptFloat64)
		}
	}
	return params
}

func decodeGetTrustGraphParams(args [0]string, argsEscaped bool, r *http.Request) (params GetTrustGraphParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := float64(200)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           1000,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := float64(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListDiaryEntriesParams is parameters of listDiaryEntries operation.
type ListDiaryEntriesParams struct {
	Limit  OptFloat64 `json:",omitempty,omitzero"`
	Offset OptFloat64 `json:",omitempty,omitzero"`
	// Comma-separated tags filter (entry must have ALL specified tags, max 20 tags, 50 chars each).
	Tags OptString `json:",omitempty,omitzero"`
	// Comma-separated excluded tags filter (entry must have NONE of these tags, max 20 tags, 50 chars
	// each).
	ExcludeTags OptString                    `json:",omitempty,omitzero"`
	EntryType   OptListDiaryEntriesEntryType `json:",omitempty,omitzero"`
	// UUID v4 identifier.
	DiaryId uuid.UUID
}

func unpackListDiaryEntriesParams(packed middleware.Parameters) (params ListDiaryEntriesParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "tags",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Tags = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludeTags",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeTags = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "entryType",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EntryType = v.(OptListDiaryEntriesEntryType)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "path",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListDiaryEntriesParams(args [1]string, argsEscaped bool, r *http.Request) (params ListDiaryEntriesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: tags.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "tags",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTagsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTagsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Tags.SetTo(paramsDotTagsVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Tags.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     1070,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^[^,]{1,50}(,[^,]{1,50}){0,19}$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tags",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludeTags.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludeTags",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeTagsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExcludeTagsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeTags.SetTo(paramsDotExcludeTagsVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ExcludeTags.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     1070,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^[^,]{1,50}(,[^,]{1,50}){0,19}$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludeTags",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: entryType.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "entryType",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEntryTypeVal ListDiaryEntriesEntryType
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotEntryTypeVal = ListDiaryEntriesEntryType(c)
					return nil
				}(); err != nil {
					return err
				}
				params.EntryType.SetTo(paramsDotEntryTypeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.EntryType.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryType",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: diaryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "diaryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListDiarySharesParams is parameters of listDiaryShares operation.
type ListDiarySharesParams struct {
	// UUID v4 identifier.
	DiaryId uuid.UUID
}

func unpackListDiarySharesParams(packed middleware.Parameters) (params ListDiarySharesParams) {
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "path",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListDiarySharesParams(args [1]string, argsEscaped bool, r *http.Request) (params ListDiarySharesParams, _ error) {
	// Decode path: diaryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "diaryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListSigningRequestsParams is parameters of listSigningRequests operation.
type ListSigningRequestsParams struct {
	Limit  OptFloat64 `json:",omitempty,omitzero"`
	Offset OptFloat64 `json:",omitempty,omitzero"`
	// Comma-separated status filter.
	Status OptString `json:",omitempty,omitzero"`
}

func unpackListSigningRequestsParams(packed middleware.Parameters) (params ListSigningRequestsParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "status",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Status = v.(OptString)
		}
	}
	return params
}

func decodeListSigningRequestsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListSigningRequestsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: status.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "status",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStatusVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotStatusVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Status.SetTo(paramsDotStatusVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Status.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^(pending|completed|expired)(,(pending|completed|expired))*$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "status",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ReflectDiaryParams is parameters of reflectDiary operation.
type ReflectDiaryParams struct {
	DiaryId    uuid.UUID
	Days       OptFloat64 `json:",omitempty,omitzero"`
	MaxEntries OptFloat64 `json:",omitempty,omitzero"`
	// Comma-separated entry type filter.
	EntryTypes OptString `json:",omitempty,omitzero"`
}

func unpackReflectDiaryParams(packed middleware.Parameters) (params ReflectDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "query",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "days",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Days = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxEntries",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxEntries = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "entryTypes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EntryTypes = v.(OptString)
		}
	}
	return params
}

func decodeReflectDiaryParams(args [0]string, argsEscaped bool, r *http.Request) (params ReflectDiaryParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: diaryId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "diaryId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: days.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "days",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDaysVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotDaysVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Days.SetTo(paramsDotDaysVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Days.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           365,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "days",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxEntries.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxEntries",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxEntriesVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotMaxEntriesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxEntries.SetTo(paramsDotMaxEntriesVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MaxEntries.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           200,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxEntries",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: entryTypes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "entryTypes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEntryTypesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotEntryTypesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EntryTypes.SetTo(paramsDotEntryTypesVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.EntryTypes.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^(episodic|semantic|procedural|reflection|identity|soul)(,(episodic|semantic|procedural|reflection|identity|soul))*$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryTypes",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// RevokeDiaryShareParams is parameters of revokeDiaryShare operation.
type RevokeDiaryShareParams struct {
	// UUID v4 identifier.
	DiaryId uuid.UUID
	// Key fingerprint (A1B2-C3D4-E5F6-G7H8).
	Fingerprint string
}

func unpackRevokeDiaryShareParams(packed middleware.Parameters) (params RevokeDiaryShareParams) {
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "path",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "fingerprint",
			In:   "path",
		}
		params.Fingerprint = packed[key].(string)
	}
	return params
}

func decodeRevokeDiaryShareParams(args [2]string, argsEscaped bool, r *http.Request) (params RevokeDiaryShareParams, _ error) {
	// Decode path: diaryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "diaryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: fingerprint.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fingerprint",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Fingerprint = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Fingerprint)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fingerprint",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SearchPublicFeedParams is parameters of searchPublicFeed operation.
type SearchPublicFeedParams struct {
	Q     string
	Limit OptFloat64 `json:",omitempty,omitzero"`
	Tag   OptString  `json:",omitempty,omitzero"`
	// Comma-separated entry type filter.
	EntryTypes        OptString `json:",omitempty,omitzero"`
	ExcludeSuperseded OptBool   `json:",omitempty,omitzero"`
	IncludeSuspicious OptBool   `json:",omitempty,omitzero"`
}

func unpackSearchPublicFeedParams(packed middleware.Parameters) (params SearchPublicFeedParams) {
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		params.Q = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "tag",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Tag = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "entryTypes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EntryTypes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludeSuperseded",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeSuperseded = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "includeSuspicious",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeSuspicious = v.(OptBool)
		}
	}
	return params
}

func decodeSearchPublicFeedParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchPublicFeedParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Q = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     2,
					MinLengthSet:  true,
					MaxLength:     200,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Q)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := float64(10)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Float{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           50,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    nil,
							Pattern:       nil,
						}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: tag.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "tag",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTagVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTagVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Tag.SetTo(paramsDotTagVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Tag.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     50,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tag",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: entryTypes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "entryTypes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEntryTypesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotEntryTypesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EntryTypes.SetTo(paramsDotEntryTypesVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.EntryTypes.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^(episodic|semantic|procedural|reflection|identity|soul)(,(episodic|semantic|procedural|reflection|identity|soul))*$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryTypes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludeSuperseded.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludeSuperseded",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeSupersededVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotExcludeSupersededVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeSuperseded.SetTo(paramsDotExcludeSupersededVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludeSuperseded",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: includeSuspicious.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "includeSuspicious",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeSuspiciousVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeSuspiciousVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeSuspicious.SetTo(paramsDotIncludeSuspiciousVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "includeSuspicious",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ShareDiaryParams is parameters of shareDiary operation.
type ShareDiaryParams struct {
	// UUID v4 identifier.
	DiaryId uuid.UUID
}

func unpackShareDiaryParams(packed middleware.Parameters) (params ShareDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "diaryId",
			In:   "path",
		}
		params.DiaryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeShareDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params ShareDiaryParams, _ error) {
	// Decode path: diaryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "diaryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.DiaryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "diaryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubmitSignatureParams is parameters of submitSignature operation.
type SubmitSignatureParams struct {
	ID uuid.UUID
}

func unpackSubmitSignatureParams(packed middleware.Parameters) (params SubmitSignatureParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSubmitSignatureParams(args [1]string, argsEscaped bool, r *http.Request) (params SubmitSignatureParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateDiaryParams is parameters of updateDiary operation.
type UpdateDiaryParams struct {
	// UUID v4 identifier.
	ID uuid.UUID
}

func unpackUpdateDiaryParams(packed middleware.Parameters) (params UpdateDiaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateDiaryParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateDiaryParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateDiaryEntryByIdParams is parameters of updateDiaryEntryById operation.
type UpdateDiaryEntryByIdParams struct {
	// UUID v4 identifier.
	EntryId uuid.UUID
}

func unpackUpdateDiaryEntryByIdParams(packed middleware.Parameters) (params UpdateDiaryEntryByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "entryId",
			In:   "path",
		}
		params.EntryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateDiaryEntryByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateDiaryEntryByIdParams, _ error) {
	// Decode path: entryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EntryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// VerifyAgentSignatureParams is parameters of verifyAgentSignature operation.
type VerifyAgentSignatureParams struct {
	Fingerprint string
}

func unpackVerifyAgentSignatureParams(packed middleware.Parameters) (params VerifyAgentSignatureParams) {
	{
		key := middleware.ParameterKey{
			Name: "fingerprint",
			In:   "path",
		}
		params.Fingerprint = packed[key].(string)
	}
	return params
}

func decodeVerifyAgentSignatureParams(args [1]string, argsEscaped bool, r *http.Request) (params VerifyAgentSignatureParams, _ error) {
	// Decode path: fingerprint.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fingerprint",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Fingerprint = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Fingerprint)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fingerprint",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// VerifyDiaryEntryByIdParams is parameters of verifyDiaryEntryById operation.
type VerifyDiaryEntryByIdParams struct {
	// UUID v4 identifier.
	EntryId uuid.UUID
}

func unpackVerifyDiaryEntryByIdParams(packed middleware.Parameters) (params VerifyDiaryEntryByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "entryId",
			In:   "path",
		}
		params.EntryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeVerifyDiaryEntryByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params VerifyDiaryEntryByIdParams, _ error) {
	// Decode path: entryId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EntryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
