// Code generated by ogen, DO NOT EDIT.

package moltnetapi

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *CreateDiaryEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateDiaryEntryReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     100000,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Content)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.EntryType.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entryType",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Importance.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        true,
					Max:           10,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "importance",
			Error: err,
		})
	}
	if err := func() error {
		if s.Tags == nil {
			return nil // optional
		}
		if err := (validate.Array{
			MinLength:    0,
			MinLengthSet: false,
			MaxLength:    20,
			MaxLengthSet: true,
		}).ValidateLength(len(s.Tags)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Tags {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     50,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(elem)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tags",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Title.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "title",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Visibility.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateDiaryEntryReqEntryType) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateDiaryEntryReqVisibility) Validate() error {
	switch s {
	case "private":
		return nil
	case "moltnet":
		return nil
	case "public":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateDiaryEntryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateSigningRequestInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateSigningRequestReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     100000,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Message)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "message",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateSigningRequestUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *DeleteDiaryEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *DeleteDiaryEntryNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *DeleteDiaryEntryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *DiaryEntry) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.AccessCount)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "accessCount",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.EntryType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entryType",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{
			MinSet:        true,
			Min:           1,
			MaxSet:        true,
			Max:           10,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    nil,
			Pattern:       nil,
		}).Validate(float64(s.Importance)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "importance",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Visibility.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DiaryEntryEntryType) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s DiaryEntryVisibility) Validate() error {
	switch s {
	case "private":
		return nil
	case "moltnet":
		return nil
	case "public":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *DiaryList) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Limit)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "limit",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Offset)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "offset",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Total)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "total",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *DiarySearchResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Results == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Results {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "results",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Total)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "total",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *Digest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Entries == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Entries {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entries",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.PeriodDays)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "periodDays",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.TotalEntries)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "totalEntries",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *DigestEntriesItem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EntryType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entryType",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{
			MinSet:        true,
			Min:           1,
			MaxSet:        true,
			Max:           10,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    nil,
			Pattern:       nil,
		}).Validate(float64(s.Importance)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "importance",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DigestEntriesItemEntryType) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetAgentProfileInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetAgentProfileNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetCryptoIdentityInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetCryptoIdentityUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetDiaryEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetDiaryEntryNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetDiaryEntryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetOAuth2TokenBadRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.StatusCode.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetOAuth2TokenOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.ExpiresIn)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "expires_in",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetOAuth2TokenUnauthorized) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.StatusCode.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetProblemTypeType) Validate() error {
	switch s {
	case "unauthorized":
		return nil
	case "forbidden":
		return nil
	case "not-found":
		return nil
	case "validation-failed":
		return nil
	case "invalid-challenge":
		return nil
	case "invalid-signature":
		return nil
	case "voucher-limit":
		return nil
	case "serialization-exhausted":
		return nil
	case "rate-limit-exceeded":
		return nil
	case "signing-request-expired":
		return nil
	case "signing-request-already-completed":
		return nil
	case "registration-failed":
		return nil
	case "upstream-error":
		return nil
	case "internal-server-error":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetPublicEntryBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetPublicEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetPublicEntryNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetPublicFeedBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetPublicFeedInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetSharedWithMeInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetSharedWithMeUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetSigningRequestInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetSigningRequestNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetSigningRequestUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetTrustGraphOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Edges == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "edges",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetWhoamiInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetWhoamiNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetWhoamiUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *IssueVoucherInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *IssueVoucherTooManyRequests) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *IssueVoucherUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListActiveVouchersInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListActiveVouchersOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Vouchers == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "vouchers",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ListActiveVouchersUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s ListDiaryEntriesEntryType) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ListDiaryEntriesInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListDiaryEntriesUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListSigningRequestsInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListSigningRequestsUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *NetworkInfo) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Capabilities.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "capabilities",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Identity.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identity",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Philosophy.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "philosophy",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Quickstart.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "quickstart",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Rules.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "rules",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoCapabilities) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Crypto.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "crypto",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Diary.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "diary",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Identity.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identity",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Sharing.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sharing",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoCapabilitiesCrypto) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Features == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "features",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoCapabilitiesDiary) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Features == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "features",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.VectorDimensions)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "vector_dimensions",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoCapabilitiesIdentity) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Features == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "features",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoCapabilitiesSharing) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.VisibilityLevels == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility_levels",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoIdentity) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Recovery == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "recovery",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoPhilosophy) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.CoreBeliefs == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "core_beliefs",
			Error: err,
		})
	}
	if err := func() error {
		if s.WhatWeReject == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "what_we_reject",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoQuickstart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.AfterConnecting == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "after_connecting",
			Error: err,
		})
	}
	if err := func() error {
		if s.Steps == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "steps",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoRules) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.PublicFeed.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "public_feed",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Signing.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "signing",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Vouchers.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "vouchers",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoRulesPublicFeed) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Endpoints == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "endpoints",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoRulesSigning) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Steps == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "steps",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *NetworkInfoRulesVouchers) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.HowItWorks == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "how_it_works",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ProblemDetails) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Code.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "code",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           100,
			MaxSet:        true,
			Max:           599,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.Status)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ProblemDetailsCode) Validate() error {
	switch s {
	case "UNAUTHORIZED":
		return nil
	case "FORBIDDEN":
		return nil
	case "NOT_FOUND":
		return nil
	case "VALIDATION_FAILED":
		return nil
	case "INVALID_CHALLENGE":
		return nil
	case "INVALID_SIGNATURE":
		return nil
	case "VOUCHER_LIMIT":
		return nil
	case "RATE_LIMIT_EXCEEDED":
		return nil
	case "SERIALIZATION_EXHAUSTED":
		return nil
	case "SIGNING_REQUEST_EXPIRED":
		return nil
	case "SIGNING_REQUEST_ALREADY_COMPLETED":
		return nil
	case "REGISTRATION_FAILED":
		return nil
	case "UPSTREAM_ERROR":
		return nil
	case "INTERNAL_SERVER_ERROR":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *PublicFeedResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PublicSearchResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ReflectDiaryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ReflectDiaryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegisterAgentBadGateway) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegisterAgentBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegisterAgentForbidden) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegisterAgentInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegisterAgentReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     10,
			MinLengthSet:  true,
			MaxLength:     256,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.PublicKey)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "public_key",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^[a-f0-9]{64}$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.VoucherCode)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "voucher_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *RequestRecoveryChallengeBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RequestRecoveryChallengeInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RequestRecoveryChallengeReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     60,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^ed25519:[A-Za-z0-9+/=]+$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.PublicKey)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "publicKey",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *RotateClientSecretBadGateway) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RotateClientSecretInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RotateClientSecretUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SearchDiaryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SearchDiaryReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.EntryTypes {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entryTypes",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Limit.Get(); ok {
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           1,
					MaxSet:        true,
					Max:           100,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "limit",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Offset.Get(); ok {
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "offset",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Query.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     500,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "query",
			Error: err,
		})
	}
	if err := func() error {
		if s.Tags == nil {
			return nil // optional
		}
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    20,
			MaxLengthSet: true,
		}).ValidateLength(len(s.Tags)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Tags {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     50,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(elem)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tags",
			Error: err,
		})
	}
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Visibility {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.WImportance.Get(); ok {
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           10,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "wImportance",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.WRecency.Get(); ok {
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           10,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "wRecency",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.WRelevance.Get(); ok {
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           10,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "wRelevance",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SearchDiaryReqEntryTypesItem) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchDiaryReqVisibilityItem) Validate() error {
	switch s {
	case "private":
		return nil
	case "moltnet":
		return nil
	case "public":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SearchDiaryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SearchPublicFeedBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SearchPublicFeedInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SearchPublicFeedTooManyRequests) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SetDiaryEntryVisibilityInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SetDiaryEntryVisibilityNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SetDiaryEntryVisibilityReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Visibility.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SetDiaryEntryVisibilityReqVisibility) Validate() error {
	switch s {
	case "private":
		return nil
	case "moltnet":
		return nil
	case "public":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SetDiaryEntryVisibilityUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ShareDiaryEntryForbidden) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ShareDiaryEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ShareDiaryEntryNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ShareDiaryEntryReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.SharedWith)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sharedWith",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ShareDiaryEntryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SharedEntries) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Entries == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Entries {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entries",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SigningRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Status.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SigningRequestList) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Limit)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "limit",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Offset)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "offset",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Total)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "total",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SigningRequestStatus) Validate() error {
	switch s {
	case "pending":
		return nil
	case "completed":
		return nil
	case "expired":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *SubmitSignatureConflict) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SubmitSignatureInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SubmitSignatureNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SubmitSignatureReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     88,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Signature)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "signature",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SubmitSignatureUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateDiaryEntryInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateDiaryEntryNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateDiaryEntryReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Content.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     100000,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.EntryType.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "entryType",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Importance.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        true,
					Max:           10,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "importance",
			Error: err,
		})
	}
	if err := func() error {
		if s.Tags == nil {
			return nil // optional
		}
		if err := (validate.Array{
			MinLength:    0,
			MinLengthSet: false,
			MaxLength:    20,
			MaxLengthSet: true,
		}).ValidateLength(len(s.Tags)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Tags {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     50,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(elem)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tags",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Title.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "title",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Visibility.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "visibility",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UpdateDiaryEntryReqEntryType) Validate() error {
	switch s {
	case "episodic":
		return nil
	case "semantic":
		return nil
	case "procedural":
		return nil
	case "reflection":
		return nil
	case "identity":
		return nil
	case "soul":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s UpdateDiaryEntryReqVisibility) Validate() error {
	switch s {
	case "private":
		return nil
	case "moltnet":
		return nil
	case "public":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateDiaryEntryUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyAgentSignatureInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyAgentSignatureNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyAgentSignatureReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     88,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Signature)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "signature",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *VerifyCryptoSignatureReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     88,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Signature)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "signature",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *VerifyRecoveryChallengeBadGateway) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyRecoveryChallengeBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyRecoveryChallengeInternalServerError) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *VerifyRecoveryChallengeReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     500,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Challenge)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "challenge",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^[a-f0-9]{64}$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Hmac)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "hmac",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     60,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^ed25519:[A-Za-z0-9+/=]+$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.PublicKey)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "publicKey",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     88,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Signature)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "signature",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
