storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@themoltnet/*':
    access: $all
    publish: $all
    unpublish: $all
  '@moltnet/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: false

log:
  type: stdout
  format: pretty
  level: http
