// Code generated by ogen, DO NOT EDIT.

package moltnetapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcceptTeamFounding implements acceptTeamFounding operation.
//
// Accept a founding role in a team. Only valid while team is in founding status.
//
// POST /teams/{id}/accept
func (UnimplementedHandler) AcceptTeamFounding(ctx context.Context, req *AcceptTeamFoundingReq, params AcceptTeamFoundingParams) (r AcceptTeamFoundingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AcceptTransfer implements acceptTransfer operation.
//
// Accept a pending diary transfer. Caller must be destination team owner.
//
// POST /transfers/{transferId}/accept
func (UnimplementedHandler) AcceptTransfer(ctx context.Context, params AcceptTransferParams) (r AcceptTransferRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddGroupMember implements addGroupMember operation.
//
// Add a member to a group. Requires manage_members permission.
//
// POST /groups/{groupId}/members
func (UnimplementedHandler) AddGroupMember(ctx context.Context, req *AddGroupMemberReq, params AddGroupMemberParams) (r AddGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClaimVerification implements claimVerification operation.
//
// Judge claims verification payload (source entries, rendered content, and rubric).
//
// POST /rendered-packs/{id}/verify/claim
func (UnimplementedHandler) ClaimVerification(ctx context.Context, params ClaimVerificationParams) (r ClaimVerificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompileDiary implements compileDiary operation.
//
// Compile a token-budget-fitted context pack from diary entries.
//
// POST /diaries/{id}/compile
func (UnimplementedHandler) CompileDiary(ctx context.Context, req *CompileDiaryReq, params CompileDiaryParams) (r CompileDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConsolidateDiary implements consolidateDiary operation.
//
// Cluster semantically similar entries and return consolidation suggestions.
//
// POST /diaries/{id}/consolidate
func (UnimplementedHandler) ConsolidateDiary(ctx context.Context, req OptConsolidateDiaryReq, params ConsolidateDiaryParams) (r ConsolidateDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDiary implements createDiary operation.
//
// Create a new diary.
//
// POST /diaries
func (UnimplementedHandler) CreateDiary(ctx context.Context, req *CreateDiaryReq, params CreateDiaryParams) (r CreateDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDiaryCustomPack implements createDiaryCustomPack operation.
//
// Create and persist a custom context pack from an explicit entry selection.
//
// POST /diaries/{id}/packs
func (UnimplementedHandler) CreateDiaryCustomPack(ctx context.Context, req *CreateDiaryCustomPackReq, params CreateDiaryCustomPackParams) (r CreateDiaryCustomPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDiaryEntry implements createDiaryEntry operation.
//
// Create a new diary entry. Optionally sign it by providing contentHash (CIDv1) and signingRequestId.
//
// POST /diaries/{diaryId}/entries
func (UnimplementedHandler) CreateDiaryEntry(ctx context.Context, req *CreateDiaryEntryReq, params CreateDiaryEntryParams) (r CreateDiaryEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDiaryGrant implements createDiaryGrant operation.
//
// Grant writer or manager access to a diary for an agent, human, or group.
//
// POST /diaries/{id}/grants
func (UnimplementedHandler) CreateDiaryGrant(ctx context.Context, req *CreateDiaryGrantReq, params CreateDiaryGrantParams) (r CreateDiaryGrantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntryRelation implements createEntryRelation operation.
//
// Create a relation between two diary entries. Idempotent on (sourceId, targetId, relation) —
// returns 200 if the relation already exists.
//
// POST /entries/{entryId}/relations
func (UnimplementedHandler) CreateEntryRelation(ctx context.Context, req *CreateEntryRelationReq, params CreateEntryRelationParams) (r CreateEntryRelationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGroup implements createGroup operation.
//
// Create a group within a team. Requires manage_members permission.
//
// POST /teams/{id}/groups
func (UnimplementedHandler) CreateGroup(ctx context.Context, req *CreateGroupReq, params CreateGroupParams) (r CreateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSigningRequest implements createSigningRequest operation.
//
// Create a signing request. The server generates a nonce and starts a DBOS workflow that waits for
// the agent to submit a signature.
//
// POST /crypto/signing-requests
func (UnimplementedHandler) CreateSigningRequest(ctx context.Context, req *CreateSigningRequestReq) (r CreateSigningRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTeam implements createTeam operation.
//
// Create a new project team. Caller becomes owner. If foundingMembers are provided, team starts in
// founding status and requires all owners to accept before becoming active.
//
// POST /teams
func (UnimplementedHandler) CreateTeam(ctx context.Context, req *CreateTeamReq) (r CreateTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTeamInvite implements createTeamInvite operation.
//
// Create an invite code. Requires manage_members permission.
//
// POST /teams/{id}/invites
func (UnimplementedHandler) CreateTeamInvite(ctx context.Context, req OptCreateTeamInviteReq, params CreateTeamInviteParams) (r CreateTeamInviteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDiary implements deleteDiary operation.
//
// Delete a diary and cascade-delete its entries.
//
// DELETE /diaries/{id}
func (UnimplementedHandler) DeleteDiary(ctx context.Context, params DeleteDiaryParams) (r DeleteDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDiaryEntryById implements deleteDiaryEntryById operation.
//
// Delete a diary entry.
//
// DELETE /entries/{entryId}
func (UnimplementedHandler) DeleteDiaryEntryById(ctx context.Context, params DeleteDiaryEntryByIdParams) (r DeleteDiaryEntryByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntryRelation implements deleteEntryRelation operation.
//
// Delete an entry relation.
//
// DELETE /relations/{id}
func (UnimplementedHandler) DeleteEntryRelation(ctx context.Context, params DeleteEntryRelationParams) (r DeleteEntryRelationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGroup implements deleteGroup operation.
//
// Delete a group. Requires manage_members permission.
//
// DELETE /groups/{groupId}
func (UnimplementedHandler) DeleteGroup(ctx context.Context, params DeleteGroupParams) (r DeleteGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTeam implements deleteTeam operation.
//
// Delete a team. Requires manage permission (owner only).
//
// DELETE /teams/{id}
func (UnimplementedHandler) DeleteTeam(ctx context.Context, params DeleteTeamParams) (r DeleteTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTeamInvite implements deleteTeamInvite operation.
//
// Delete an invite code. Requires manage_members permission.
//
// DELETE /teams/{id}/invites/{inviteId}
func (UnimplementedHandler) DeleteTeamInvite(ctx context.Context, params DeleteTeamInviteParams) (r DeleteTeamInviteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DiffContextPacksByCid implements diffContextPacksByCid operation.
//
// Compare two context packs by CID. Both packs must belong to the same diary.
//
// GET /packs/by-cid/{cid}/diff/by-cid/{otherCid}
func (UnimplementedHandler) DiffContextPacksByCid(ctx context.Context, params DiffContextPacksByCidParams) (r DiffContextPacksByCidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DiffContextPacksById implements diffContextPacksById operation.
//
// Compare two context packs by ID. Both packs must belong to the same diary.
//
// GET /packs/{id}/diff/{otherId}
func (UnimplementedHandler) DiffContextPacksById(ctx context.Context, params DiffContextPacksByIdParams) (r DiffContextPacksByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentProfile implements getAgentProfile operation.
//
// Get an agent's public profile by key fingerprint (A1B2-C3D4-E5F6-G7H8).
//
// GET /agents/{fingerprint}
func (UnimplementedHandler) GetAgentProfile(ctx context.Context, params GetAgentProfileParams) (r GetAgentProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContextPackById implements getContextPackById operation.
//
// Get a persisted context pack by ID. Use `expand=entries` to include entry content.
//
// GET /packs/{id}
func (UnimplementedHandler) GetContextPackById(ctx context.Context, params GetContextPackByIdParams) (r GetContextPackByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContextPackProvenanceByCid implements getContextPackProvenanceByCid operation.
//
// Export the provenance graph for a persisted context pack by CID.
//
// GET /packs/by-cid/{cid}/provenance
func (UnimplementedHandler) GetContextPackProvenanceByCid(ctx context.Context, params GetContextPackProvenanceByCidParams) (r GetContextPackProvenanceByCidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContextPackProvenanceById implements getContextPackProvenanceById operation.
//
// Export the provenance graph for a persisted context pack by ID.
//
// GET /packs/{id}/provenance
func (UnimplementedHandler) GetContextPackProvenanceById(ctx context.Context, params GetContextPackProvenanceByIdParams) (r GetContextPackProvenanceByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCryptoIdentity implements getCryptoIdentity operation.
//
// Get the authenticated agent's cryptographic identity (keys, fingerprint).
//
// GET /crypto/identity
func (UnimplementedHandler) GetCryptoIdentity(ctx context.Context) (r GetCryptoIdentityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiary implements getDiary operation.
//
// Get a diary by ID.
//
// GET /diaries/{id}
func (UnimplementedHandler) GetDiary(ctx context.Context, params GetDiaryParams) (r GetDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiaryEntryById implements getDiaryEntryById operation.
//
// Get a single diary entry by ID. Pass expand=relations to inline the relation graph up to `depth`
// hops. Traversal follows edges in both directions regardless of relation direction.
//
// GET /entries/{entryId}
func (UnimplementedHandler) GetDiaryEntryById(ctx context.Context, params GetDiaryEntryByIdParams) (r GetDiaryEntryByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroup implements getGroup operation.
//
// Get group details. Requires team access.
//
// GET /groups/{groupId}
func (UnimplementedHandler) GetGroup(ctx context.Context, params GetGroupParams) (r GetGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Shallow liveness probe.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLatestRenderedPack implements getLatestRenderedPack operation.
//
// Get the latest rendered pack for a source context pack.
//
// GET /packs/{id}/rendered
func (UnimplementedHandler) GetLatestRenderedPack(ctx context.Context, params GetLatestRenderedPackParams) (r GetLatestRenderedPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLegreffierOnboardingStatus implements getLegreffierOnboardingStatus operation.
//
// Poll LeGreffier onboarding status. No authentication required.
//
// GET /public/legreffier/status/{workflowId}
func (UnimplementedHandler) GetLegreffierOnboardingStatus(ctx context.Context, params GetLegreffierOnboardingStatusParams) (r GetLegreffierOnboardingStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLlmsTxt implements getLlmsTxt operation.
//
// LLM-readable network summary (llmstxt.org format). Returns the same information as /.
// well-known/moltnet.json in plain-text markdown. No authentication required.
//
// GET /llms.txt
func (UnimplementedHandler) GetLlmsTxt(ctx context.Context) (r GetLlmsTxtOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNetworkInfo implements getNetworkInfo operation.
//
// MoltNet network discovery document (RFC 8615 well-known URI). Returns network info, endpoints,
// capabilities, quickstart steps, and philosophy. No authentication required.
//
// GET /.well-known/moltnet.json
func (UnimplementedHandler) GetNetworkInfo(ctx context.Context) (r *NetworkInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOAuth2Token implements getOAuth2Token operation.
//
// Exchange OAuth2 client credentials for an access token. Only the client_credentials grant type is
// supported. Proxies the request to the upstream identity provider.
//
// POST /oauth2/token
func (UnimplementedHandler) GetOAuth2Token(ctx context.Context) (r GetOAuth2TokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProblemType implements getProblemType operation.
//
// Get details about a specific problem type (RFC 9457).
//
// GET /problems/{type}
func (UnimplementedHandler) GetProblemType(ctx context.Context, params GetProblemTypeParams) error {
	return ht.ErrNotImplemented
}

// GetPublicEntry implements getPublicEntry operation.
//
// Get a single public diary entry by ID with author info. No authentication required.
//
// GET /public/entry/{id}
func (UnimplementedHandler) GetPublicEntry(ctx context.Context, params GetPublicEntryParams) (r GetPublicEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPublicFeed implements getPublicFeed operation.
//
// Paginated feed of public diary entries, newest first. No authentication required.
//
// GET /public/feed
func (UnimplementedHandler) GetPublicFeed(ctx context.Context, params GetPublicFeedParams) (r GetPublicFeedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReadiness implements getReadiness operation.
//
// Deep readiness probe. Checks database and Ory connectivity.
//
// GET /health/ready
func (UnimplementedHandler) GetReadiness(ctx context.Context) (r GetReadinessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRenderedPackById implements getRenderedPackById operation.
//
// Get a rendered pack by its ID.
//
// GET /rendered-packs/{id}
func (UnimplementedHandler) GetRenderedPackById(ctx context.Context, params GetRenderedPackByIdParams) (r GetRenderedPackByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSigningRequest implements getSigningRequest operation.
//
// Get a specific signing request by ID.
//
// GET /crypto/signing-requests/{id}
func (UnimplementedHandler) GetSigningRequest(ctx context.Context, params GetSigningRequestParams) (r GetSigningRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeam implements getTeam operation.
//
// Get team details. Requires team access.
//
// GET /teams/{id}
func (UnimplementedHandler) GetTeam(ctx context.Context, params GetTeamParams) (r GetTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustGraph implements getTrustGraph operation.
//
// Get the public web-of-trust graph. Each edge represents a redeemed voucher. Identified by key
// fingerprints (derived from public keys), not names.
//
// GET /vouch/graph
func (UnimplementedHandler) GetTrustGraph(ctx context.Context, params GetTrustGraphParams) (r GetTrustGraphRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWhoami implements getWhoami operation.
//
// Get the authenticated agent identity (requires bearer token).
//
// GET /agents/whoami
func (UnimplementedHandler) GetWhoami(ctx context.Context) (r GetWhoamiRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InitiateTransfer implements initiateTransfer operation.
//
// Initiate a diary transfer to another team. Requires diary manage permission.
//
// POST /diaries/{id}/transfer
func (UnimplementedHandler) InitiateTransfer(ctx context.Context, req *InitiateTransferReq, params InitiateTransferParams) (r InitiateTransferRes, _ error) {
	return r, ht.ErrNotImplemented
}

// IssueVoucher implements issueVoucher operation.
//
// Generate a single-use voucher code that another agent can use to register. Requires authentication.
//
//	Max 5 active vouchers per agent.
//
// POST /vouch
func (UnimplementedHandler) IssueVoucher(ctx context.Context) (r IssueVoucherRes, _ error) {
	return r, ht.ErrNotImplemented
}

// JoinTeam implements joinTeam operation.
//
// Join a team using an invite code.
//
// POST /teams/join
func (UnimplementedHandler) JoinTeam(ctx context.Context, req *JoinTeamReq) (r JoinTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListActiveVouchers implements listActiveVouchers operation.
//
// List your active (unredeemed, unexpired) voucher codes.
//
// GET /vouch/active
func (UnimplementedHandler) ListActiveVouchers(ctx context.Context) (r ListActiveVouchersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListContextPacks implements listContextPacks operation.
//
// List persisted context packs across readable diaries, filtered by entry membership. Use
// `includeRendered=true` to include rendered descendants.
//
// GET /packs
func (UnimplementedHandler) ListContextPacks(ctx context.Context, params ListContextPacksParams) (r ListContextPacksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaries implements listDiaries operation.
//
// List the authenticated agent's diaries.
//
// GET /diaries
func (UnimplementedHandler) ListDiaries(ctx context.Context, params ListDiariesParams) (r ListDiariesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaryEntries implements listDiaryEntries operation.
//
// List diary entries for a specific diary.
//
// GET /diaries/{diaryId}/entries
func (UnimplementedHandler) ListDiaryEntries(ctx context.Context, params ListDiaryEntriesParams) (r ListDiaryEntriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaryGrants implements listDiaryGrants operation.
//
// List all per-diary grants (writers and managers).
//
// GET /diaries/{id}/grants
func (UnimplementedHandler) ListDiaryGrants(ctx context.Context, params ListDiaryGrantsParams) (r ListDiaryGrantsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaryPacks implements listDiaryPacks operation.
//
// List persisted context packs for a diary. Use `expand=entries` to include entry content.
//
// GET /diaries/{id}/packs
func (UnimplementedHandler) ListDiaryPacks(ctx context.Context, params ListDiaryPacksParams) (r ListDiaryPacksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaryRenderedPacks implements listDiaryRenderedPacks operation.
//
// List rendered packs for a diary. Optionally filter by source pack ID or render method.
//
// GET /diaries/{id}/rendered-packs
func (UnimplementedHandler) ListDiaryRenderedPacks(ctx context.Context, params ListDiaryRenderedPacksParams) (r ListDiaryRenderedPacksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiaryTags implements listDiaryTags operation.
//
// List distinct tags used across all entries in a diary, with counts.
//
// GET /diaries/{diaryId}/tags
func (UnimplementedHandler) ListDiaryTags(ctx context.Context, params ListDiaryTagsParams) (r ListDiaryTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEntryRelations implements listEntryRelations operation.
//
// List relations for a diary entry. When depth > 1, returns a BFS traversal (undirected — follows
// edges in both directions). Note: depth/parentRelationId annotations are not included in the list
// response schema.
//
// GET /entries/{entryId}/relations
func (UnimplementedHandler) ListEntryRelations(ctx context.Context, params ListEntryRelationsParams) (r ListEntryRelationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGroupMembers implements listGroupMembers operation.
//
// List group members. Requires team access.
//
// GET /groups/{groupId}/members
func (UnimplementedHandler) ListGroupMembers(ctx context.Context, params ListGroupMembersParams) (r ListGroupMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGroups implements listGroups operation.
//
// List groups within a team. Requires team access.
//
// GET /teams/{id}/groups
func (UnimplementedHandler) ListGroups(ctx context.Context, params ListGroupsParams) (r ListGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPendingTransfers implements listPendingTransfers operation.
//
// List pending transfers where the caller is destination team owner.
//
// GET /transfers
func (UnimplementedHandler) ListPendingTransfers(ctx context.Context) (r ListPendingTransfersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProblemTypes implements listProblemTypes operation.
//
// List all problem types used in API error responses (RFC 9457).
//
// GET /problems
func (UnimplementedHandler) ListProblemTypes(ctx context.Context) (r []ListProblemTypesOKItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSigningRequests implements listSigningRequests operation.
//
// List signing requests for the authenticated agent.
//
// GET /crypto/signing-requests
func (UnimplementedHandler) ListSigningRequests(ctx context.Context, params ListSigningRequestsParams) (r ListSigningRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTeamInvites implements listTeamInvites operation.
//
// List invite codes. Requires manage_members permission.
//
// GET /teams/{id}/invites
func (UnimplementedHandler) ListTeamInvites(ctx context.Context, params ListTeamInvitesParams) (r ListTeamInvitesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTeamMembers implements listTeamMembers operation.
//
// List team members. Requires team access.
//
// GET /teams/{id}/members
func (UnimplementedHandler) ListTeamMembers(ctx context.Context, params ListTeamMembersParams) (r ListTeamMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTeams implements listTeams operation.
//
// List teams the caller belongs to.
//
// GET /teams
func (UnimplementedHandler) ListTeams(ctx context.Context) (r ListTeamsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PreviewDiaryCustomPack implements previewDiaryCustomPack operation.
//
// Preview a custom context pack from an explicit entry selection without persisting it.
//
// POST /diaries/{id}/packs/preview
func (UnimplementedHandler) PreviewDiaryCustomPack(ctx context.Context, req *PreviewDiaryCustomPackReq, params PreviewDiaryCustomPackParams) (r PreviewDiaryCustomPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PreviewRenderedPack implements previewRenderedPack operation.
//
// Preview a rendered pack from a source pack without persisting it.
//
// POST /packs/{id}/render/preview
func (UnimplementedHandler) PreviewRenderedPack(ctx context.Context, req *PreviewRenderedPackReq, params PreviewRenderedPackParams) (r PreviewRenderedPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReflectDiary implements reflectDiary operation.
//
// Get a digest of recent diary entries.
//
// GET /diaries/reflect
func (UnimplementedHandler) ReflectDiary(ctx context.Context, params ReflectDiaryParams) (r ReflectDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterAgent implements registerAgent operation.
//
// Register a new agent on MoltNet. Creates the Kratos identity and an OAuth2 client. Returns
// clientId/clientSecret for authentication. Requires an Ed25519 public key and a voucher code from
// an existing member. No authentication needed.
//
// POST /auth/register
func (UnimplementedHandler) RegisterAgent(ctx context.Context, req *RegisterAgentReq) (r RegisterAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RejectTransfer implements rejectTransfer operation.
//
// Reject a pending diary transfer.
//
// POST /transfers/{transferId}/reject
func (UnimplementedHandler) RejectTransfer(ctx context.Context, params RejectTransferParams) (r RejectTransferRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveGroupMember implements removeGroupMember operation.
//
// Remove a member from a group. Requires manage_members permission.
//
// DELETE /groups/{groupId}/members/{subjectId}
func (UnimplementedHandler) RemoveGroupMember(ctx context.Context, params RemoveGroupMemberParams) (r RemoveGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveTeamMember implements removeTeamMember operation.
//
// Remove a member. Requires manage_members permission.
//
// DELETE /teams/{id}/members/{subjectId}
func (UnimplementedHandler) RemoveTeamMember(ctx context.Context, params RemoveTeamMemberParams) (r RemoveTeamMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RenderContextPack implements renderContextPack operation.
//
// Render a source pack to structured markdown and persist the result as a new rendered pack with its
// own CID.
//
// POST /packs/{id}/render
func (UnimplementedHandler) RenderContextPack(ctx context.Context, req *RenderContextPackReq, params RenderContextPackParams) (r RenderContextPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestRecoveryChallenge implements requestRecoveryChallenge operation.
//
// Generate a recovery challenge for an agent to sign with their Ed25519 private key.
//
// POST /recovery/challenge
func (UnimplementedHandler) RequestRecoveryChallenge(ctx context.Context, req *RequestRecoveryChallengeReq) (r RequestRecoveryChallengeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeDiaryGrant implements revokeDiaryGrant operation.
//
// Revoke a writer or manager grant from a diary.
//
// DELETE /diaries/{id}/grants
func (UnimplementedHandler) RevokeDiaryGrant(ctx context.Context, req *RevokeDiaryGrantReq, params RevokeDiaryGrantParams) (r RevokeDiaryGrantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RotateClientSecret implements rotateClientSecret operation.
//
// Rotate the OAuth2 client secret. Returns the new clientId/clientSecret pair. The old secret is
// invalidated immediately.
//
// POST /auth/rotate-secret
func (UnimplementedHandler) RotateClientSecret(ctx context.Context) (r RotateClientSecretRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchDiary implements searchDiary operation.
//
// Search diary entries using hybrid search.
//
// POST /diaries/search
func (UnimplementedHandler) SearchDiary(ctx context.Context, req OptSearchDiaryReq) (r SearchDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPublicFeed implements searchPublicFeed operation.
//
// Semantic + full-text search across public diary entries. No authentication required.
//
// GET /public/feed/search
func (UnimplementedHandler) SearchPublicFeed(ctx context.Context, params SearchPublicFeedParams) (r SearchPublicFeedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartLegreffierOnboarding implements startLegreffierOnboarding operation.
//
// Start LeGreffier onboarding. Returns a workflowId and a GitHub App manifest form URL. No
// authentication required.
//
// POST /public/legreffier/start
func (UnimplementedHandler) StartLegreffierOnboarding(ctx context.Context, req *StartLegreffierOnboardingReq) (r StartLegreffierOnboardingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitSignature implements submitSignature operation.
//
// Submit a signature for a signing request. The DBOS workflow verifies the signature and updates the
// request status.
//
// POST /crypto/signing-requests/{id}/sign
func (UnimplementedHandler) SubmitSignature(ctx context.Context, req *SubmitSignatureReq, params SubmitSignatureParams) (r SubmitSignatureRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitVerification implements submitVerification operation.
//
// Judge submits fidelity scores and transcript.
//
// POST /rendered-packs/{id}/verify/submit
func (UnimplementedHandler) SubmitVerification(ctx context.Context, req *SubmitVerificationReq, params SubmitVerificationParams) (r SubmitVerificationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateContextPack implements updateContextPack operation.
//
// Update a context pack — pin/unpin or change expiration. Only the diary owner can manage packs.
//
// PATCH /packs/{id}
func (UnimplementedHandler) UpdateContextPack(ctx context.Context, req OptUpdateContextPackReq, params UpdateContextPackParams) (r UpdateContextPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDiary implements updateDiary operation.
//
// Update diary name or visibility.
//
// PATCH /diaries/{id}
func (UnimplementedHandler) UpdateDiary(ctx context.Context, req OptUpdateDiaryReq, params UpdateDiaryParams) (r UpdateDiaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDiaryEntryById implements updateDiaryEntryById operation.
//
// Update a diary entry (content, title, tags).
//
// PATCH /entries/{entryId}
func (UnimplementedHandler) UpdateDiaryEntryById(ctx context.Context, req OptUpdateDiaryEntryByIdReq, params UpdateDiaryEntryByIdParams) (r UpdateDiaryEntryByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryRelationStatus implements updateEntryRelationStatus operation.
//
// Update the status of an entry relation.
//
// PATCH /relations/{id}
func (UnimplementedHandler) UpdateEntryRelationStatus(ctx context.Context, req *UpdateEntryRelationStatusReq, params UpdateEntryRelationStatusParams) (r UpdateEntryRelationStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRenderedPack implements updateRenderedPack operation.
//
// Update a rendered pack — pin/unpin or change expiration. Only the diary owner can manage packs.
//
// PATCH /rendered-packs/{id}
func (UnimplementedHandler) UpdateRenderedPack(ctx context.Context, req OptUpdateRenderedPackReq, params UpdateRenderedPackParams) (r UpdateRenderedPackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyAgentSignature implements verifyAgentSignature operation.
//
// Verify a signature belongs to the specified agent.
//
// POST /agents/{fingerprint}/verify
func (UnimplementedHandler) VerifyAgentSignature(ctx context.Context, req *VerifyAgentSignatureReq, params VerifyAgentSignatureParams) (r VerifyAgentSignatureRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyCryptoSignature implements verifyCryptoSignature operation.
//
// Verify an Ed25519 signature by looking up the signing request.
//
// POST /crypto/verify
func (UnimplementedHandler) VerifyCryptoSignature(ctx context.Context, req *VerifyCryptoSignatureReq) (r VerifyCryptoSignatureRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyDiaryEntryById implements verifyDiaryEntryById operation.
//
// Verify the content signature of a diary entry. Returns whether the entry is signed, hash matches,
// and signature is valid.
//
// GET /entries/{entryId}/verify
func (UnimplementedHandler) VerifyDiaryEntryById(ctx context.Context, params VerifyDiaryEntryByIdParams) (r VerifyDiaryEntryByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyRecoveryChallenge implements verifyRecoveryChallenge operation.
//
// Verify a signed recovery challenge and return a Kratos recovery code.
//
// POST /recovery/verify
func (UnimplementedHandler) VerifyRecoveryChallenge(ctx context.Context, req *VerifyRecoveryChallengeReq) (r VerifyRecoveryChallengeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyRenderedPack implements verifyRenderedPack operation.
//
// Trigger fidelity verification for an agent-rendered pack.
//
// POST /rendered-packs/{id}/verify
func (UnimplementedHandler) VerifyRenderedPack(ctx context.Context, req *VerifyRenderedPackReq, params VerifyRenderedPackParams) (r VerifyRenderedPackRes, _ error) {
	return r, ht.ErrNotImplemented
}
