/**
 * GENERATED — DO NOT EDIT BY HAND. Run `node scripts/generate-gtfobins.mjs`.
 *
 * Vendored from GTFOBins (https://gtfobins.github.io/), GPL-3.0-or-later:
 *   https://github.com/GTFOBins/GTFOBins.github.io @ acd524623f9c406acedd2754ebd9c2431f3675ad
 *
 * Maps each GTFOBins binary to the abuse functions it documents (shell,
 * command, reverse-shell, file-read, file-write, sudo, suid, …). Presence in
 * this map classifies a resolved executable as `escapable`; the function list
 * is surfaced to the policy layer and any downstream LLM judge.
 */

/** GTFOBins commit this snapshot was generated from. */
export const GTFOBINS_SOURCE_COMMIT =
  'acd524623f9c406acedd2754ebd9c2431f3675ad';

/** Binary name → GTFOBins abuse functions. */
export const GTFOBINS: Readonly<Record<string, readonly string[]>> = {
  '7z': ['file-read'],
  R: ['shell'],
  'aa-exec': ['shell'],
  ab: ['download', 'upload'],
  acr: ['command'],
  agetty: ['shell'],
  alpine: ['file-read'],
  'ansible-playbook': ['shell'],
  'ansible-test': ['shell'],
  aoss: ['shell'],
  apache2: ['file-read'],
  apache2ctl: ['file-read'],
  'apport-cli': ['inherit'],
  apt: ['inherit', 'shell'],
  'apt-get': ['inherit', 'shell'],
  aptitude: ['inherit'],
  ar: ['file-read'],
  'arch-nspawn': ['shell'],
  aria2c: ['command', 'download', 'file-read'],
  arj: ['file-read', 'file-write'],
  arp: ['file-read'],
  as: ['file-read'],
  'ascii-xfr': ['file-read'],
  ascii85: ['file-read'],
  ash: ['file-write', 'shell'],
  aspell: ['file-read'],
  asterisk: ['shell'],
  at: ['command', 'shell'],
  atobm: ['file-read'],
  autoconf: ['shell'],
  autoheader: ['shell'],
  autoreconf: ['shell'],
  awk: ['file-read', 'file-write', 'shell'],
  aws: ['file-read', 'inherit'],
  base32: ['file-read'],
  base58: ['file-read'],
  base64: ['file-read'],
  basenc: ['file-read'],
  basez: ['file-read'],
  bash: [
    'download',
    'file-read',
    'file-write',
    'library-load',
    'reverse-shell',
    'shell',
    'upload',
  ],
  bashbug: ['inherit'],
  batcat: ['inherit'],
  bbot: ['file-read'],
  bc: ['file-read'],
  bconsole: ['file-read', 'shell'],
  bee: ['inherit'],
  borg: ['shell'],
  bpftrace: ['shell'],
  bridge: ['file-read'],
  bundle: ['inherit', 'shell'],
  bundler: ['inherit', 'shell'],
  busctl: ['inherit', 'shell'],
  busybox: ['inherit', 'reverse-shell', 'upload'],
  byebug: ['inherit'],
  bzip2: ['file-read'],
  c89: ['file-read', 'file-write', 'shell'],
  c99: ['file-read', 'file-write', 'shell'],
  cabal: ['shell'],
  cancel: ['upload'],
  capsh: ['shell'],
  cargo: ['inherit'],
  cat: ['file-read'],
  cc: ['file-read', 'file-write', 'shell'],
  cdist: ['shell'],
  certbot: ['shell'],
  chattr: ['privilege-escalation'],
  check_by_ssh: ['shell'],
  check_cups: ['file-read'],
  check_log: ['file-read', 'file-write'],
  check_memory: ['file-read'],
  check_raid: ['file-read'],
  check_ssl_cert: ['shell'],
  check_statusfile: ['file-read'],
  chmod: ['privilege-escalation'],
  choom: ['shell'],
  chown: ['privilege-escalation'],
  chroot: ['shell'],
  chrt: ['shell'],
  clamscan: ['file-read'],
  clisp: ['shell'],
  cmake: ['file-read', 'shell'],
  cmp: ['file-read'],
  cobc: ['shell'],
  code: ['download', 'reverse-shell', 'upload'],
  codex: ['shell'],
  column: ['file-read'],
  comm: ['file-read'],
  composer: ['shell'],
  cowsay: ['inherit'],
  cowthink: ['inherit'],
  cp: ['file-read', 'file-write', 'privilege-escalation'],
  cpan: ['inherit'],
  cpio: ['file-read', 'file-write', 'shell'],
  cpulimit: ['shell'],
  crash: ['command', 'inherit'],
  crontab: ['command', 'inherit'],
  csh: ['file-write', 'shell'],
  csplit: ['file-read', 'file-write'],
  csvtool: ['file-read', 'file-write', 'shell'],
  ctr: ['shell'],
  cupsfilter: ['file-read'],
  curl: ['download', 'file-read', 'file-write', 'library-load', 'upload'],
  cut: ['file-read'],
  dash: ['file-write', 'shell'],
  date: ['file-read'],
  dc: ['shell'],
  dd: ['file-read', 'file-write'],
  debugfs: ['shell'],
  dhclient: ['shell'],
  dialog: ['file-read'],
  diff: ['file-read'],
  dig: ['file-read'],
  distcc: ['shell'],
  dmesg: ['file-read', 'inherit'],
  dmidecode: ['file-write'],
  dmsetup: ['shell'],
  dnf: ['command'],
  dnsmasq: ['command'],
  doas: ['shell'],
  docker: ['file-read', 'file-write', 'shell'],
  dos2unix: ['file-read', 'file-write'],
  dosbox: ['file-read', 'file-write'],
  dotnet: ['file-read', 'shell'],
  dpkg: ['inherit', 'shell'],
  dstat: ['inherit'],
  dvips: ['shell'],
  easy_install: ['inherit'],
  easyrsa: ['shell'],
  eb: ['inherit'],
  ed: ['file-read', 'file-write', 'shell'],
  efax: ['file-read'],
  egrep: ['file-read'],
  elvish: ['file-read', 'file-write', 'shell'],
  emacs: ['file-read', 'file-write', 'shell'],
  enscript: ['shell'],
  env: ['shell'],
  eqn: ['file-read'],
  espeak: ['file-read'],
  ex: ['inherit', 'shell'],
  exiftool: ['file-read', 'file-write', 'inherit'],
  expand: ['file-read'],
  expect: ['file-read', 'shell'],
  facter: ['inherit'],
  'fail2ban-client': ['command'],
  fastfetch: ['command', 'file-read', 'shell'],
  ffmpeg: ['library-load'],
  fgrep: ['file-read'],
  file: ['file-read'],
  find: ['file-read', 'file-write', 'shell'],
  finger: ['download', 'upload'],
  firejail: ['shell'],
  fish: ['shell'],
  flock: ['shell'],
  fmt: ['file-read'],
  fold: ['file-read'],
  forge: ['shell'],
  fping: ['file-read'],
  ftp: ['download', 'shell', 'upload'],
  fzf: ['command', 'shell'],
  'g++': ['file-read', 'file-write', 'shell'],
  gawk: ['bind-shell', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  gcc: ['file-read', 'file-write', 'shell'],
  gcloud: ['inherit'],
  gcore: ['file-read'],
  gdb: ['file-write', 'inherit', 'shell'],
  gem: ['inherit', 'shell'],
  genie: ['shell'],
  genisoimage: ['file-read'],
  getent: ['privilege-escalation'],
  ghc: ['shell'],
  ghci: ['shell'],
  gimp: ['inherit'],
  ginsh: ['shell'],
  git: ['file-read', 'file-write', 'inherit', 'shell'],
  gnuplot: ['shell'],
  go: ['bind-shell', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  grc: ['shell'],
  grep: ['file-read'],
  gtester: ['file-write', 'shell'],
  guile: ['shell'],
  gzip: ['file-read'],
  hashcat: ['file-write'],
  hd: ['file-read'],
  head: ['file-read'],
  hexdump: ['file-read'],
  hg: ['shell'],
  highlight: ['file-read'],
  hping3: ['shell', 'upload'],
  iconv: ['file-read', 'file-write'],
  iftop: ['shell'],
  install: ['privilege-escalation'],
  ionice: ['shell'],
  ip: ['file-read', 'shell'],
  'iptables-save': ['file-write'],
  irb: ['inherit'],
  ispell: ['shell'],
  java: ['shell'],
  jjs: ['download', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  joe: ['shell'],
  join: ['file-read'],
  journalctl: ['inherit'],
  jq: ['file-read'],
  jrunscript: ['download', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  jshell: ['file-read', 'file-write', 'shell'],
  jtag: ['shell'],
  julia: ['download', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  knife: ['inherit'],
  ksh: [
    'download',
    'file-read',
    'file-write',
    'library-load',
    'reverse-shell',
    'shell',
    'upload',
  ],
  ksshell: ['file-read'],
  ksu: ['shell'],
  kubectl: ['shell', 'upload'],
  last: ['file-read'],
  lastb: ['file-read'],
  latex: ['file-read', 'file-write', 'shell'],
  latexmk: ['file-read', 'inherit', 'shell'],
  'ld.so': ['shell'],
  ldconfig: ['library-load'],
  less: ['command', 'file-read', 'file-write', 'inherit', 'shell'],
  lftp: ['shell'],
  links: ['file-read'],
  ln: ['privilege-escalation'],
  loginctl: ['shell'],
  logrotate: ['file-read', 'file-write', 'shell'],
  logsave: ['shell'],
  look: ['file-read'],
  lp: ['upload'],
  ltrace: ['file-read', 'file-write', 'shell'],
  lua: [
    'bind-shell',
    'download',
    'file-read',
    'file-write',
    'reverse-shell',
    'shell',
    'upload',
  ],
  lualatex: ['inherit'],
  luatex: ['inherit'],
  'lwp-download': ['download', 'file-read', 'file-write'],
  'lwp-request': ['file-read'],
  lxd: ['shell'],
  m4: ['command', 'file-read', 'shell'],
  mail: ['shell'],
  make: ['file-read', 'file-write', 'shell'],
  man: ['file-read', 'inherit', 'shell'],
  mawk: ['file-read', 'file-write', 'shell'],
  minicom: ['shell'],
  more: ['file-read', 'shell'],
  'mosh-server': ['shell'],
  mosquitto: ['file-read'],
  mount: ['privilege-escalation'],
  msfconsole: ['inherit'],
  msgattrib: ['file-read'],
  msgcat: ['file-read'],
  msgconv: ['file-read'],
  msgfilter: ['file-read', 'shell'],
  msgmerge: ['file-read'],
  msguniq: ['file-read'],
  mtr: ['file-read'],
  multitime: ['shell'],
  mutt: ['file-read'],
  mv: ['file-write', 'privilege-escalation'],
  mypy: ['file-read', 'file-write'],
  mysql: ['library-load', 'shell'],
  nano: ['file-read', 'file-write', 'shell'],
  nasm: ['file-read'],
  nawk: ['bind-shell', 'file-read', 'file-write', 'reverse-shell', 'shell'],
  nc: ['bind-shell', 'download', 'reverse-shell', 'upload'],
  ncdu: ['shell'],
  ncftp: ['shell'],
  needrestart: ['inherit'],
  neofetch: ['file-read', 'shell'],
  nft: ['file-read'],
  nginx: ['download', 'library-load', 'upload'],
  nice: ['shell'],
  nl: ['file-read'],
  nm: ['file-read'],
  nmap: ['file-read', 'file-write', 'inherit', 'shell'],
  node: [
    'bind-shell',
    'download',
    'file-read',
    'file-write',
    'reverse-shell',
    'shell',
    'upload',
  ],
  nohup: ['command', 'shell'],
  npm: ['shell'],
  nroff: ['file-read', 'shell'],
  nsenter: ['shell'],
  ntpdate: ['file-read'],
  nvim: ['file-read', 'inherit'],
  octave: ['file-read', 'file-write', 'shell'],
  od: ['file-read'],
  opencode: ['command', 'inherit'],
  openssl: [
    'download',
    'file-read',
    'file-write',
    'library-load',
    'reverse-shell',
    'upload',
  ],
  openvpn: ['file-read', 'shell'],
  openvt: ['command'],
  opkg: ['shell'],
  pandoc: ['file-read', 'file-write', 'inherit'],
  passwd: ['privilege-escalation'],
  paste: ['file-read'],
  pax: ['file-read'],
  pdb: ['inherit'],
  pdflatex: ['file-read', 'file-write', 'shell'],
  pdftex: ['shell'],
  perf: ['shell'],
  perl: ['download', 'file-read', 'reverse-shell', 'shell', 'upload'],
  perlbug: ['shell'],
  pexec: ['shell'],
  pg: ['file-read', 'shell'],
  php: [
    'command',
    'download',
    'file-read',
    'file-write',
    'reverse-shell',
    'shell',
    'upload',
  ],
  pic: ['file-read', 'shell'],
  pico: ['file-read', 'file-write', 'shell'],
  pidstat: ['shell'],
  pip: ['inherit', 'shell'],
  pipx: ['inherit'],
  pkexec: ['shell'],
  pkg: ['command'],
  plymouth: ['shell'],
  podman: ['shell'],
  poetry: ['inherit'],
  posh: ['shell'],
  pr: ['file-read'],
  procmail: ['command'],
  pry: ['inherit'],
  psftp: ['shell'],
  psql: ['inherit', 'shell'],
  ptx: ['file-read'],
  puppet: ['file-read', 'file-write', 'shell'],
  pwsh: ['file-write', 'shell'],
  pygmentize: ['file-read'],
  pyright: ['file-read'],
  python: [
    'download',
    'file-read',
    'file-write',
    'library-load',
    'reverse-shell',
    'shell',
    'upload',
  ],
  qpdf: ['file-read'],
  rake: ['file-read', 'inherit'],
  ranger: ['shell'],
  rc: ['shell'],
  readelf: ['file-read'],
  red: ['file-read', 'file-write', 'shell'],
  redcarpet: ['file-read'],
  redis: ['file-write'],
  restic: ['command', 'shell', 'upload'],
  rev: ['file-read'],
  rlogin: ['upload'],
  rlwrap: ['file-write', 'shell'],
  rpm: ['command', 'inherit', 'shell'],
  rpmdb: ['inherit', 'shell'],
  rpmquery: ['inherit', 'shell'],
  rpmverify: ['inherit', 'shell'],
  rsync: ['shell'],
  rsyslogd: ['command'],
  rtorrent: ['shell'],
  ruby: [
    'download',
    'file-read',
    'file-write',
    'library-load',
    'reverse-shell',
    'shell',
    'upload',
  ],
  'run-mailcap': ['inherit'],
  'run-parts': ['shell'],
  runscript: ['shell'],
  rustc: ['file-read', 'file-write', 'inherit'],
  rustdoc: ['file-read', 'file-write'],
  rustfmt: ['file-read'],
  rustup: ['command', 'shell'],
  rview: ['file-read', 'inherit'],
  rvim: ['file-read', 'inherit'],
  sash: ['shell'],
  scanmem: ['shell'],
  scp: ['download', 'shell', 'upload'],
  screen: ['file-write', 'shell'],
  script: ['file-write', 'shell'],
  scrot: ['shell'],
  sed: ['file-read', 'file-write', 'shell'],
  service: ['shell'],
  setarch: ['shell'],
  setcap: ['privilege-escalation'],
  setfacl: ['privilege-escalation'],
  setlock: ['shell'],
  sftp: ['download', 'shell', 'upload'],
  sg: ['shell'],
  shred: ['file-write'],
  shuf: ['file-read', 'file-write'],
  slsh: ['shell'],
  smbclient: ['download', 'shell', 'upload'],
  snap: ['command'],
  socat: [
    'bind-shell',
    'download',
    'file-read',
    'file-write',
    'reverse-shell',
    'shell',
    'upload',
  ],
  socket: ['bind-shell', 'reverse-shell'],
  soelim: ['file-read'],
  softlimit: ['shell'],
  sort: ['file-read', 'file-write'],
  split: ['file-read', 'file-write', 'shell'],
  sqlite3: ['file-read', 'file-write', 'shell'],
  sqlmap: ['inherit'],
  ss: ['file-read'],
  ssh: ['download', 'file-read', 'shell', 'upload'],
  'ssh-agent': ['shell'],
  'ssh-copy-id': ['file-read', 'file-write'],
  'ssh-keygen': ['library-load'],
  'ssh-keyscan': ['file-read'],
  sshfs: ['command', 'download', 'shell', 'upload'],
  sshpass: ['shell'],
  sshuttle: ['shell'],
  'start-stop-daemon': ['shell'],
  stdbuf: ['shell'],
  strace: ['file-write', 'shell'],
  strings: ['file-read'],
  su: ['shell'],
  sudo: ['shell'],
  sysctl: ['command', 'file-read'],
  systemctl: ['inherit', 'shell'],
  'systemd-resolve': ['inherit'],
  'systemd-run': ['command', 'shell'],
  tac: ['file-read'],
  tail: ['file-read'],
  tailscale: ['upload'],
  tar: ['download', 'file-read', 'file-write', 'shell', 'upload'],
  task: ['shell'],
  taskset: ['shell'],
  tasksh: ['shell'],
  tbl: ['file-read'],
  tclsh: ['library-load', 'reverse-shell', 'shell'],
  tcpdump: ['command', 'file-write'],
  tcsh: ['file-write', 'shell'],
  tdbtool: ['shell'],
  tee: ['file-write'],
  telnet: ['reverse-shell', 'shell'],
  terraform: ['file-read'],
  tex: ['shell'],
  tftp: ['download', 'upload'],
  tic: ['file-read'],
  time: ['shell'],
  timedatectl: ['inherit'],
  timeout: ['shell'],
  tmate: ['shell'],
  tmux: ['file-read', 'shell'],
  top: ['shell'],
  torify: ['shell'],
  torsocks: ['shell'],
  troff: ['file-read'],
  tsc: ['file-read', 'file-write'],
  tshark: ['inherit'],
  ul: ['file-read'],
  unexpand: ['file-read'],
  uniq: ['file-read'],
  unshare: ['shell'],
  unsquashfs: ['privilege-escalation'],
  unzip: ['privilege-escalation'],
  'update-alternatives': ['file-write'],
  urlget: ['file-read'],
  uuencode: ['file-read'],
  uv: ['shell'],
  vagrant: ['inherit'],
  valgrind: ['shell'],
  varnishncsa: ['file-write'],
  vi: ['file-read', 'file-write', 'shell'],
  view: ['file-read', 'inherit'],
  vigr: ['inherit'],
  vim: ['file-read', 'inherit'],
  vimdiff: ['file-read', 'inherit'],
  vipw: ['inherit'],
  virsh: ['command', 'file-write'],
  volatility: ['inherit'],
  w3m: ['file-read'],
  wall: ['file-read'],
  watch: ['shell'],
  wc: ['file-read'],
  'wg-quick': ['shell'],
  wget: ['download', 'file-read', 'file-write', 'shell', 'upload'],
  whiptail: ['file-read'],
  whois: ['download', 'upload'],
  wireshark: ['file-write', 'inherit'],
  wish: ['inherit'],
  xargs: ['file-read', 'shell'],
  'xdg-user-dir': ['shell'],
  xdotool: ['shell'],
  xelatex: ['file-read', 'file-write', 'shell'],
  xetex: ['shell'],
  xmodmap: ['file-read'],
  xmore: ['file-read'],
  xpad: ['file-read'],
  xxd: ['file-read', 'file-write'],
  xz: ['file-read'],
  yarn: ['shell'],
  yash: ['shell'],
  yelp: ['file-read'],
  'yt-dlp': ['shell'],
  yum: ['command', 'download', 'inherit'],
  zathura: ['shell'],
  zcat: ['file-read'],
  zgrep: ['file-read'],
  zic: ['command'],
  zip: ['file-read', 'shell'],
  zless: ['inherit'],
  zsh: [
    'download',
    'file-read',
    'file-write',
    'inherit',
    'reverse-shell',
    'shell',
    'upload',
  ],
  zsoelim: ['file-read'],
  zypper: ['shell'],
};
