package configmigrate

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"github.com/getlarge/themoltnet/apps/moltnet-cli/internal/safefile"
)

const PlanFormat = 1

type PlannedMigration struct {
	ID          string   `json:"id"`
	Description string   `json:"description"`
	Operations  []string `json:"operations"`
}

type Plan struct {
	FormatVersion   int                `json:"formatVersion"`
	GeneratedBy     string             `json:"generatedBy"`
	CredentialsPath string             `json:"credentialsPath"`
	ConfigSHA256    string             `json:"configSha256"`
	Migrations      []PlannedMigration `json:"migrations"`
}

type Failure struct {
	Migration              string `json:"migration"`
	Stage                  string `json:"stage"`
	Retryable              bool   `json:"retryable"`
	ManualRecoveryRequired bool   `json:"manualRecoveryRequired"`
	Message                string `json:"message"`
	Changed                bool   `json:"-"`
}

type RunOutput struct {
	Plan                   Plan     `json:"plan"`
	Applied                []string `json:"applied"`
	Changed                bool     `json:"changed"`
	Failure                *Failure `json:"failure,omitempty"`
	ManualRecoveryRequired bool     `json:"manualRecoveryRequired"`
}

type Context struct {
	CredentialsPath     string
	CredentialsDocument []byte
	maxConfigBytes      int64
	lock                *safefile.Lock
}

func (c Context) ReplaceCredentials(updated []byte) error {
	if c.lock == nil {
		return fmt.Errorf("credentials replacement requires the migration lock")
	}
	return c.lock.Replace(c.CredentialsDocument, updated, c.maxConfigBytes)
}

type Migration[T any] struct {
	ID          string
	Description string
	Operations  []string
	Applies     func(Context) (bool, error)
	Run         func(Context, T) error
}

type Engine[T any] struct {
	GeneratedBy    string
	MaxConfigBytes int64
	Migrations     []Migration[T]
}

func (e Engine[T]) BuildPlan(credentialsPath string) (Plan, error) {
	document, err := ReadBoundedRegularFile(credentialsPath, e.MaxConfigBytes)
	if err != nil {
		return Plan{}, fmt.Errorf("read credentials for migration: %w", err)
	}
	return e.buildPlanFromDocument(credentialsPath, document)
}

func (e Engine[T]) buildPlanFromDocument(credentialsPath string, document []byte) (Plan, error) {
	if err := validateMigrations(e.Migrations); err != nil {
		return Plan{}, err
	}
	plan := Plan{
		FormatVersion:   PlanFormat,
		GeneratedBy:     e.GeneratedBy,
		CredentialsPath: credentialsPath,
		ConfigSHA256:    documentSHA256(document),
		Migrations:      make([]PlannedMigration, 0, 1),
	}
	ctx := Context{
		CredentialsPath:     credentialsPath,
		CredentialsDocument: document,
		maxConfigBytes:      e.MaxConfigBytes,
	}
	for _, migration := range e.Migrations {
		applies, err := migration.Applies(ctx)
		if err != nil {
			return Plan{}, fmt.Errorf("plan config migration %q: %w", migration.ID, err)
		}
		if !applies {
			continue
		}
		plan.Migrations = append(plan.Migrations, PlannedMigration{
			ID:          migration.ID,
			Description: migration.Description,
			Operations:  append([]string(nil), migration.Operations...),
		})
		break
	}
	return plan, nil
}

func (e Engine[T]) Apply(plan Plan, runtime T) ([]string, error) {
	if plan.FormatVersion != PlanFormat {
		return nil, fmt.Errorf("unsupported migration plan format %d", plan.FormatVersion)
	}
	if plan.GeneratedBy != e.GeneratedBy {
		return nil, fmt.Errorf("migration plan was generated by %q, not %q", plan.GeneratedBy, e.GeneratedBy)
	}
	if len(plan.Migrations) > 1 {
		return nil, fmt.Errorf("migration plans may contain at most one transition")
	}
	if err := validateMigrations(e.Migrations); err != nil {
		return nil, err
	}

	lock, err := safefile.Acquire(plan.CredentialsPath)
	if err != nil {
		return nil, fmt.Errorf("lock credentials for migration: %w", err)
	}
	defer lock.Close()

	document, err := ReadBoundedRegularFile(plan.CredentialsPath, e.MaxConfigBytes)
	if err != nil {
		return nil, fmt.Errorf("read credentials for migration: %w", err)
	}
	if documentSHA256(document) != plan.ConfigSHA256 {
		return nil, fmt.Errorf("credentials changed after the migration plan was generated; generate a new plan")
	}
	expected, err := e.buildPlanFromDocument(plan.CredentialsPath, document)
	if err != nil {
		return nil, err
	}
	if !equalPlannedMigrations(plan.Migrations, expected.Migrations) {
		return nil, fmt.Errorf("migration plan does not match the next transition for these credentials; generate a new plan")
	}
	if len(plan.Migrations) == 0 {
		return nil, nil
	}

	planned := plan.Migrations[0]
	for _, migration := range e.Migrations {
		if migration.ID != planned.ID {
			continue
		}
		ctx := Context{
			CredentialsPath:     plan.CredentialsPath,
			CredentialsDocument: document,
			maxConfigBytes:      e.MaxConfigBytes,
			lock:                lock,
		}
		if err := migration.Run(ctx, runtime); err != nil {
			return nil, fmt.Errorf("apply config migration %q: %w", migration.ID, err)
		}
		return []string{migration.ID}, nil
	}
	return nil, fmt.Errorf("migration plan references unknown transition %q", planned.ID)
}

func validateMigrations[T any](migrations []Migration[T]) error {
	seen := make(map[string]struct{}, len(migrations))
	for _, migration := range migrations {
		if strings.TrimSpace(migration.ID) == "" || migration.Applies == nil || migration.Run == nil {
			return fmt.Errorf("config migration definitions require an id, applicability check, and run function")
		}
		if _, exists := seen[migration.ID]; exists {
			return fmt.Errorf("duplicate config migration id %q", migration.ID)
		}
		seen[migration.ID] = struct{}{}
	}
	return nil
}

type StageError struct {
	Stage                  string
	Retryable              bool
	ManualRecoveryRequired bool
	Changed                bool
	Err                    error
}

type FailureState struct {
	Retryable              bool
	Changed                bool
	ManualRecoveryRequired bool
}

func (e *StageError) Error() string { return e.Err.Error() }
func (e *StageError) Unwrap() error { return e.Err }

func NewStageError(stage string, state FailureState, err error) error {
	return &StageError{
		Stage:                  stage,
		Retryable:              state.Retryable,
		Changed:                state.Changed,
		ManualRecoveryRequired: state.ManualRecoveryRequired,
		Err:                    err,
	}
}

func FailureFromError(plan Plan, err error) *Failure {
	failure := &Failure{
		Stage:     "apply",
		Retryable: true,
		Message:   "configuration migration failed during apply",
	}
	if len(plan.Migrations) == 1 {
		failure.Migration = plan.Migrations[0].ID
	}
	var stageErr *StageError
	if errors.As(err, &stageErr) {
		failure.Stage = stageErr.Stage
		failure.Retryable = stageErr.Retryable
		failure.Changed = stageErr.Changed
		failure.ManualRecoveryRequired = stageErr.ManualRecoveryRequired
		failure.Message = "configuration migration failed during " + stageErr.Stage
	}
	return failure
}

func documentSHA256(document []byte) string {
	digest := sha256.Sum256(document)
	return hex.EncodeToString(digest[:])
}

func equalPlannedMigrations(left, right []PlannedMigration) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index].ID != right[index].ID ||
			left[index].Description != right[index].Description ||
			!equalStrings(left[index].Operations, right[index].Operations) {
			return false
		}
	}
	return true
}

func equalStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}
