package configmigrate

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const testMaxConfigBytes = 1 << 20

func testEngine(migrations []Migration[struct{}]) Engine[struct{}] {
	return Engine[struct{}]{
		GeneratedBy:    "moltnet@test",
		MaxConfigBytes: testMaxConfigBytes,
		Migrations:     migrations,
	}
}

func stateMigration(id, from, to string, ran *[]string) Migration[struct{}] {
	return Migration[struct{}]{
		ID:          id,
		Description: "migration " + id,
		Operations:  []string{"transition " + from + " to " + to},
		Applies: func(ctx Context) (bool, error) {
			return string(ctx.CredentialsDocument) == from, nil
		},
		Run: func(ctx Context, _ struct{}) error {
			*ran = append(*ran, id)
			return ctx.ReplaceCredentials([]byte(to))
		},
	}
}

func writeState(t *testing.T, state string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "moltnet.json")
	if err := os.WriteFile(path, []byte(state), privateFileMode); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestEnginePlansOneTransitionFromCurrentState(t *testing.T) {
	t.Run("predecessor enables successor", func(t *testing.T) {
		path := writeState(t, "0")
		var ran []string
		engine := testEngine([]Migration[struct{}]{
			stateMigration("first", "0", "1", &ran),
			stateMigration("second", "1", "2", &ran),
		})

		first, err := engine.BuildPlan(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := plannedIDs(first); got != "first" {
			t.Fatalf("first plan = %q", got)
		}
		if _, err := engine.Apply(first, struct{}{}); err != nil {
			t.Fatal(err)
		}
		second, err := engine.BuildPlan(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := plannedIDs(second); got != "second" {
			t.Fatalf("second plan = %q", got)
		}
	})

	t.Run("predecessor disables successor", func(t *testing.T) {
		path := writeState(t, "0")
		var ran []string
		engine := testEngine([]Migration[struct{}]{
			stateMigration("first", "0", "2", &ran),
			stateMigration("second", "1", "3", &ran),
		})

		plan, err := engine.BuildPlan(path)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := engine.Apply(plan, struct{}{}); err != nil {
			t.Fatal(err)
		}
		next, err := engine.BuildPlan(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := plannedIDs(next); got != "" {
			t.Fatalf("next plan = %q", got)
		}
	})
}

func TestEngineRejectsTamperedPlansBeforeMutation(t *testing.T) {
	path := writeState(t, "0")
	var ran []string
	engine := testEngine([]Migration[struct{}]{stateMigration("first", "0", "1", &ran)})
	original, err := engine.BuildPlan(path)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name   string
		mutate func(*Plan)
		want   string
	}{
		{name: "unsupported format", mutate: func(plan *Plan) { plan.FormatVersion++ }, want: "unsupported migration plan format"},
		{name: "different generator", mutate: func(plan *Plan) { plan.GeneratedBy = "moltnet@other" }, want: "migration plan was generated by"},
		{name: "omitted transition", mutate: func(plan *Plan) { plan.Migrations = nil }, want: "does not match"},
		{name: "unknown transition", mutate: func(plan *Plan) { plan.Migrations[0].ID = "unknown" }, want: "does not match"},
		{name: "changed metadata", mutate: func(plan *Plan) { plan.Migrations[0].Operations = []string{"tampered"} }, want: "does not match"},
		{name: "multiple transitions", mutate: func(plan *Plan) { plan.Migrations = append(plan.Migrations, plan.Migrations[0]) }, want: "at most one"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ran = nil
			plan := clonePlan(t, original)
			tt.mutate(&plan)
			_, err := engine.Apply(plan, struct{}{})
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("apply error = %v, want %q", err, tt.want)
			}
			if len(ran) != 0 {
				t.Fatalf("invalid plan ran migrations: %v", ran)
			}
		})
	}
}

func TestEngineRejectsStaleAndSymlinkedCredentials(t *testing.T) {
	t.Run("stale plan", func(t *testing.T) {
		path := writeState(t, "0")
		var ran []string
		engine := testEngine([]Migration[struct{}]{stateMigration("first", "0", "1", &ran)})
		plan, err := engine.BuildPlan(path)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte("changed"), privateFileMode); err != nil {
			t.Fatal(err)
		}
		if _, err := engine.Apply(plan, struct{}{}); err == nil || !strings.Contains(err.Error(), "changed after") {
			t.Fatalf("stale plan error = %v", err)
		}
	})

	t.Run("symlink", func(t *testing.T) {
		root := t.TempDir()
		target := filepath.Join(root, "target.json")
		link := filepath.Join(root, "moltnet.json")
		if err := os.WriteFile(target, []byte("0"), privateFileMode); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(target, link); err != nil {
			t.Fatal(err)
		}
		if _, err := testEngine([]Migration[struct{}]{}).BuildPlan(link); err == nil || !strings.Contains(err.Error(), "symbolic link") {
			t.Fatalf("symlink error = %v", err)
		}
	})
}

func TestFailureFromErrorPreservesStageAndRollback(t *testing.T) {
	plan := Plan{Migrations: []PlannedMigration{{ID: "first"}}}
	err := NewStageError(
		"replace_credentials",
		"secret-retained-source-changed",
		true,
		fmt.Errorf("provider included secret %q", "do-not-disclose"),
	)

	failure := FailureFromError(plan, err)

	if failure.Migration != "first" || failure.Stage != "replace_credentials" ||
		failure.Rollback != "secret-retained-source-changed" || !failure.Retryable {
		t.Fatalf("failure = %+v", failure)
	}
	if strings.Contains(failure.Message, "do-not-disclose") {
		t.Fatalf("failure disclosed provider error: %+v", failure)
	}
}

func plannedIDs(plan Plan) string {
	ids := make([]string, len(plan.Migrations))
	for index, migration := range plan.Migrations {
		ids[index] = migration.ID
	}
	return strings.Join(ids, ",")
}

func clonePlan(t *testing.T, plan Plan) Plan {
	t.Helper()
	data, err := json.Marshal(plan)
	if err != nil {
		t.Fatal(err)
	}
	var clone Plan
	if err := json.Unmarshal(data, &clone); err != nil {
		t.Fatal(err)
	}
	return clone
}
