import type { Agent } from '@themoltnet/sdk';
import { describe, expect, it, vi } from 'vitest';

import {
  applyModelExclusions,
  inspectReviewDiff,
  MAX_RAW_DIFF_BYTES,
  printablePreflight,
  stageReviewManifest,
} from './review-input.js';

const MODIFIED = `diff --git a/src/a.ts b/src/a.ts
index 1111111..2222222 100644
--- a/src/a.ts
+++ b/src/a.ts
@@ -1 +1,2 @@
-const a = 1;
+const a = 2;
+export { a };
`;

describe('inspectReviewDiff', () => {
  it('parses additions and deletions with language and trusted lanes', () => {
    const inspected = inspectReviewDiff(MODIFIED);
    expect(inspected).toMatchObject({
      version: 1,
      totalFiles: 1,
      reviewableFiles: 1,
      changedLoc: 3,
      requiresPlanning: false,
    });
    expect(inspected.files[0]).toMatchObject({
      path: 'src/a.ts',
      status: 'modified',
      additions: 2,
      deletions: 1,
      language: 'typescript',
      reviewable: true,
    });
    expect(inspected.files[0].requiredLanes).toEqual([
      'correctness',
      'dry-codebase-fit',
      'design-api-backcompat',
    ]);
  });

  it('adds specialist lanes only for high-confidence path or content signals', () => {
    const paths = [
      'src/auth/credential-service.ts',
      'src/queue/worker.ts',
      'src/api/policy.test.ts',
    ];
    const diff = paths
      .map(
        (path, index) => `diff --git a/${path} b/${path}
--- a/${path}
+++ b/${path}
@@ -1 +1 @@
-const value = 1;
+${index === 0 ? 'export const policyToken = 2;' : index === 1 ? 'const queue = workerPool;' : 'expect(policy).toBeAllowed();'}
`,
      )
      .join('');

    const inspected = inspectReviewDiff(diff);

    expect(inspected.files[0].requiredLanes).toEqual(
      expect.arrayContaining([
        'correctness',
        'dry-codebase-fit',
        'security',
        'design-api-backcompat',
      ]),
    );
    expect(inspected.files[1].requiredLanes).toEqual(
      expect.arrayContaining([
        'correctness',
        'dry-codebase-fit',
        'performance',
        'operability',
      ]),
    );
    expect(inspected.files[2].requiredLanes).toEqual([
      'correctness',
      'dry-codebase-fit',
      'tests',
    ]);
  });

  it('adds tests and readability for large authored code patches', () => {
    const removed = Array.from(
      { length: 60 },
      (_, index) => `-const oldValue${index} = ${index};`,
    ).join('\n');
    const added = Array.from(
      { length: 60 },
      (_, index) => `+const newValue${index} = ${index};`,
    ).join('\n');
    const diff = `diff --git a/src/large.ts b/src/large.ts
--- a/src/large.ts
+++ b/src/large.ts
@@ -1,60 +1,60 @@
${removed}
${added}
`;

    const inspected = inspectReviewDiff(diff);

    expect(inspected.files[0].requiredLanes).toEqual([
      'correctness',
      'dry-codebase-fit',
      'tests',
      'readability',
    ]);
  });

  it('parses deletions, renames, quoted paths, and binaries', () => {
    const diff = `diff --git a/old.ts b/old.ts
deleted file mode 100644
--- a/old.ts
+++ /dev/null
@@ -1 +0,0 @@
-old
diff --git a/from.ts b/to.ts
similarity index 100%
rename from from.ts
rename to to.ts
diff --git "a/src/hello\\040world.ts" "b/src/hello\\040world.ts"
--- "a/src/hello\\040world.ts"
+++ "b/src/hello\\040world.ts"
@@ -1 +1 @@
-old
+new
diff --git a/image.png b/image.png
new file mode 100644
Binary files /dev/null and b/image.png differ
`;
    const inspected = inspectReviewDiff(diff);
    expect(
      inspected.files.map((file) => [
        file.path,
        file.previousPath,
        file.status,
        file.binary,
      ]),
    ).toEqual([
      ['old.ts', undefined, 'deleted', false],
      ['to.ts', 'from.ts', 'renamed', false],
      ['src/hello world.ts', undefined, 'modified', false],
      ['image.png', undefined, 'added', true],
    ]);
    expect(inspected.coverage.excludedFiles).toEqual([
      { path: 'image.png', reason: 'binary', source: 'intrinsic' },
    ]);
  });

  it('does not exclude files from repository or ecosystem path conventions', () => {
    const paths = [
      'packages/acme-client/src/generated/sdk.gen.ts',
      'services/catalog/drizzle/meta/0001_snapshot.json',
      'services/orders/public/openapi.json',
      'pnpm-lock.yaml',
      'services/catalog/drizzle/0042_add_topic.sql',
      'src/header.ts',
    ];
    const diff = paths
      .map(
        (path, index) => `diff --git a/${path} b/${path}
--- a/${path}
+++ b/${path}
@@ -1 +1 @@
-old
+${index === 5 ? '// Code generated by tool. DO NOT EDIT.' : 'new'}
`,
      )
      .join('');
    const inspected = inspectReviewDiff(diff);
    expect(inspected.files.every((file) => file.reviewable)).toBe(true);
    expect(inspected.files.map((file) => file.exclusionReason)).toEqual(
      paths.map(() => undefined),
    );
    expect(inspected.files.at(-1)?.generatedSignals).toEqual([
      'generated-header',
    ]);
  });

  it('leaves arbitrary generated-looking paths for semantic model classification', () => {
    const paths = [
      'vendor/client/oas_models.go',
      'sdk/python/generated/models.py',
      'modules/example/types.generated.ts',
      'api/swagger.json',
    ];
    const diff = paths
      .map(
        (path) => `diff --git a/${path} b/${path}
--- a/${path}
+++ b/${path}
@@ -1 +1 @@
-old
+new
`,
      )
      .join('');
    expect(inspectReviewDiff(diff).reviewableFiles).toBe(paths.length);
  });

  it('uses paginated GitHub metadata for statuses and LOC', () => {
    const inspected = inspectReviewDiff(MODIFIED, [
      {
        filename: 'src/a.ts',
        status: 'modified',
        additions: 20,
        deletions: 10,
        changes: 30,
      },
    ]);
    expect(inspected.files[0]).toMatchObject({
      additions: 20,
      deletions: 10,
      changedLoc: 30,
    });
  });

  it('rejects malformed and truncated diffs before staging', () => {
    expect(() => inspectReviewDiff('not a diff')).toThrow(/before the first/);
    expect(() =>
      inspectReviewDiff(`diff --git a/a.ts b/a.ts
--- a/a.ts
+++ b/a.ts
@@ -1,2 +1,2 @@
-old
+new
`),
    ).toThrow(/truncated/);
    expect(() =>
      inspectReviewDiff(MODIFIED, [
        {
          filename: 'missing.ts',
          status: 'modified',
          additions: 1,
          deletions: 1,
          changes: 2,
        },
      ]),
    ).toThrow(/missing section/);
    expect(() => inspectReviewDiff('x'.repeat(MAX_RAW_DIFF_BYTES + 1))).toThrow(
      /ingestion limit/,
    );
  });

  it('prints preflight without patch bodies', () => {
    const printable = printablePreflight(inspectReviewDiff(MODIFIED));
    expect(printable.files[0]).not.toHaveProperty('patch');
    expect(printable.limits).toMatchObject({
      rawDiffBytes: MAX_RAW_DIFF_BYTES,
      files: 200,
      topics: 12,
      primaryFilesPerTopic: 12,
      topicReviewTasks: 12,
    });
    expect(printable.planningThresholds).toEqual({
      files: 25,
      changedLoc: 1_500,
      reviewableBytes: 64 * 1024,
    });
  });
});

describe('stageReviewManifest', () => {
  it('stages one compact manifest before model classification', async () => {
    const diff = `${MODIFIED}diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -1 +1 @@
-old
+new
`;
    const stage = vi.fn().mockResolvedValueOnce({
      cid: 'manifest-cid',
      contentType: 'application/json',
      sizeBytes: 500,
    });
    const agent = {
      tasks: { artifacts: { stage } },
    } as unknown as Agent;
    const manifest = await stageReviewManifest(
      agent,
      'team',
      inspectReviewDiff(diff),
    );
    expect(stage).toHaveBeenCalledTimes(1);
    expect(manifest.files[0]).not.toHaveProperty('artifact');
    expect(manifest.files[1]).not.toHaveProperty('artifact');
    expect(manifest.files[0].patchSha256).toMatch(/^[0-9a-f]{64}$/);
    expect(manifest.coverage.excludedFiles).toEqual([]);

    const classified = applyModelExclusions(manifest, [
      {
        path: 'pnpm-lock.yaml',
        reason: 'machine-derived dependency resolution',
        evidence: 'The patch contains resolved dependency graph data.',
      },
    ]);
    expect(classified.files[1]).toMatchObject({
      reviewable: false,
      generated: true,
    });
    expect(classified.coverage.excludedFiles).toEqual([
      {
        path: 'pnpm-lock.yaml',
        reason: 'machine-derived dependency resolution',
        evidence: 'The patch contains resolved dependency graph data.',
        source: 'model',
      },
    ]);
  });

  it('rejects unknown and duplicate model exclusion paths', () => {
    const manifest = {
      ...printablePreflight(inspectReviewDiff(MODIFIED)),
      files: [
        {
          ...printablePreflight(inspectReviewDiff(MODIFIED)).files[0],
        },
      ],
      manifestArtifact: {
        cid: 'manifest',
        title: 'review-manifest.v1.json',
        contentType: 'application/json',
        sizeBytes: 1,
      },
    };
    const decision = {
      reason: 'derived',
      evidence: 'content proves it',
    };
    expect(() =>
      applyModelExclusions(manifest, [{ path: 'missing.ts', ...decision }]),
    ).toThrow(/unknown file/);
    expect(() =>
      applyModelExclusions(manifest, [
        { path: 'src/a.ts', ...decision },
        { path: 'src/a.ts', ...decision },
      ]),
    ).toThrow(/duplicate paths/);
  });
});
