package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// runConfigExportEnvCmd reads a moltnet.json and prints MOLTNET_* env vars
// in dotenv format. The output is directly usable with init-from-env --env-file.
func runConfigExportEnvCmd(w io.Writer, credPath, outFile string, includeGitHubPEM, showSecret bool) error {
	return runConfigExportEnvCmdWithRegistry(
		w,
		credPath,
		outFile,
		includeGitHubPEM,
		showSecret,
		NewSecretProviderRegistry(),
	)
}

func runConfigExportEnvCmdWithRegistry(
	w io.Writer,
	credPath, outFile string,
	includeGitHubPEM, showSecret bool,
	secretProviders *SecretProviderRegistry,
) error {
	if includeGitHubPEM && outFile == "" {
		return fmt.Errorf("--include-github-pem requires --output")
	}
	creds, err := loadCredentials(credPath)
	if err != nil {
		return err
	}
	if creds == nil {
		return fmt.Errorf("no config found at %s", credPath)
	}
	includeSecrets := outFile != "" || showSecret
	clientSecret := ""
	if includeSecrets {
		clientSecret, err = resolveOAuth2Secret(creds, secretProviders)
		if err != nil {
			return fmt.Errorf("resolve OAuth2 client secret: %w", err)
		}
	}

	// Central paths select an identity for the exported process. Legacy bundle
	// paths retain MOLTNET_AGENT_NAME solely so their explicit export/import
	// migration workflow remains usable; neither is automatic discovery.
	agentName := ""
	parentDir := filepath.Base(filepath.Dir(credPath))
	grandparentDir := filepath.Base(filepath.Dir(filepath.Dir(credPath)))
	if (grandparentDir == "identities" || grandparentDir == ".moltnet") && parentDir != "" && parentDir != "." {
		agentName = parentDir
	}

	var lines []string
	lines = append(lines, "# Generated by moltnet config export-env")
	if agentName != "" {
		if grandparentDir == "identities" {
			lines = append(lines, fmt.Sprintf("MOLTNET_ACTIVE_IDENTITY=%s", agentName))
		} else {
			lines = append(lines, fmt.Sprintf("MOLTNET_AGENT_NAME=%s", agentName))
		}
	}
	lines = append(lines, fmt.Sprintf("MOLTNET_IDENTITY_ID=%s", creds.IdentityID))
	lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_ID=%s", creds.OAuth2.ClientID))
	if includeSecrets {
		lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_SECRET=%s", clientSecret))
	}
	lines = append(lines, fmt.Sprintf("MOLTNET_PUBLIC_KEY=%s", creds.Keys.PublicKey))
	// A host signing broker owns the seed; never export it from a guest.
	if includeSecrets && strings.TrimSpace(os.Getenv(signerURLEnv)) == "" {
		seed := creds.Keys.PrivateKey
		if creds.Keys.PrivateKeyRef != nil || seed != "" {
			resolved, err := resolveIdentitySeed(creds, secretProviders)
			if err != nil {
				return fmt.Errorf("resolve private key: %w", err)
			}
			seed = resolved
		}
		lines = append(lines, fmt.Sprintf("MOLTNET_PRIVATE_KEY=%s", seed))
	}
	lines = append(lines, fmt.Sprintf("MOLTNET_FINGERPRINT=%s", creds.Keys.Fingerprint))
	lines = append(lines, fmt.Sprintf("MOLTNET_API_URL=%s", creds.Endpoints.API))
	if creds.RegisteredAt != "" {
		lines = append(lines, fmt.Sprintf("MOLTNET_REGISTERED_AT=%s", creds.RegisteredAt))
	}

	if creds.Git != nil {
		if creds.Git.Name != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GIT_NAME=%q", creds.Git.Name))
		}
		if creds.Git.Email != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GIT_EMAIL=%q", creds.Git.Email))
		}
	}

	if creds.GitHub != nil {
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_ID=%s", creds.GitHub.AppID))
		if creds.GitHub.AppSlug != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_SLUG=%s", creds.GitHub.AppSlug))
		}
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_INSTALLATION_ID=%s", creds.GitHub.InstallationID))
		if includeGitHubPEM && (creds.GitHub.PrivateKeyPath != "" || creds.GitHub.PrivateKeyRef != nil) {
			pem, err := resolveGitHubAppPrivateKey(creds, secretProviders)
			if err != nil {
				return fmt.Errorf("resolve GitHub App PEM: %w", err)
			}
			// Dotenv multi-line: wrap in double quotes with literal newlines
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_PRIVATE_KEY=%q", strings.TrimSpace(string(pem))))
		}
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")

	if outFile != "" {
		if err := writeFileAtomic(outFile, []byte(content)); err != nil {
			return fmt.Errorf("write env file atomically: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Env vars written to %s\n", outFile)
		return nil
	}

	fmt.Fprint(w, content)
	return nil
}
