package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// runConfigExportEnvCmd reads a moltnet.json and prints MOLTNET_* env vars
// in dotenv format. The output is directly usable with init-from-env --env-file.
func runConfigExportEnvCmd(w io.Writer, credPath, outFile string, includeGitHubPEM bool) error {
	return runConfigExportEnvCmdWithRegistry(
		w,
		credPath,
		outFile,
		includeGitHubPEM,
		NewSecretProviderRegistry(),
	)
}

func runConfigExportEnvCmdWithRegistry(
	w io.Writer,
	credPath, outFile string,
	includeGitHubPEM bool,
	secretProviders *SecretProviderRegistry,
) error {
	creds, err := loadCredentials(credPath)
	if err != nil {
		return err
	}
	if creds == nil {
		return fmt.Errorf("no config found at %s", credPath)
	}
	clientSecret, err := resolveOAuth2Secret(creds, secretProviders)
	if err != nil {
		return fmt.Errorf("resolve OAuth2 client secret: %w", err)
	}

	// Derive agent name from credential path when it matches .moltnet/<agent>/moltnet.json.
	// Arbitrary paths (e.g. ~/.config/moltnet/moltnet.json) are not agent directories,
	// so we only emit MOLTNET_AGENT_NAME when the parent-of-parent is ".moltnet".
	agentName := ""
	parentDir := filepath.Base(filepath.Dir(credPath))
	grandparentDir := filepath.Base(filepath.Dir(filepath.Dir(credPath)))
	if grandparentDir == ".moltnet" && parentDir != "" && parentDir != "." {
		agentName = parentDir
	}

	var lines []string
	lines = append(lines, "# Generated by moltnet config export-env")
	if agentName != "" {
		lines = append(lines, fmt.Sprintf("MOLTNET_AGENT_NAME=%s", agentName))
	}
	lines = append(lines, fmt.Sprintf("MOLTNET_IDENTITY_ID=%s", creds.IdentityID))
	lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_ID=%s", creds.OAuth2.ClientID))
	lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_SECRET=%s", clientSecret))
	lines = append(lines, fmt.Sprintf("MOLTNET_PUBLIC_KEY=%s", creds.Keys.PublicKey))
	lines = append(lines, fmt.Sprintf("MOLTNET_PRIVATE_KEY=%s", creds.Keys.PrivateKey))
	lines = append(lines, fmt.Sprintf("MOLTNET_FINGERPRINT=%s", creds.Keys.Fingerprint))
	lines = append(lines, fmt.Sprintf("MOLTNET_API_URL=%s", creds.Endpoints.API))
	if creds.RegisteredAt != "" {
		lines = append(lines, fmt.Sprintf("MOLTNET_REGISTERED_AT=%s", creds.RegisteredAt))
	}

	if creds.Git != nil {
		if creds.Git.Name != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GIT_NAME=%q", creds.Git.Name))
		}
		if creds.Git.Email != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GIT_EMAIL=%q", creds.Git.Email))
		}
	}

	if creds.GitHub != nil {
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_ID=%s", creds.GitHub.AppID))
		if creds.GitHub.AppSlug != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_SLUG=%s", creds.GitHub.AppSlug))
		}
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_INSTALLATION_ID=%s", creds.GitHub.InstallationID))
		if includeGitHubPEM && creds.GitHub.PrivateKeyPath != "" {
			pem, err := os.ReadFile(creds.GitHub.PrivateKeyPath)
			if err != nil {
				return fmt.Errorf("read GitHub App PEM %q: %w", creds.GitHub.PrivateKeyPath, err)
			}
			// Dotenv multi-line: wrap in double quotes with literal newlines
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_PRIVATE_KEY=%q", strings.TrimSpace(string(pem))))
		}
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")

	if outFile != "" {
		file, err := os.OpenFile(outFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
		if err != nil {
			return fmt.Errorf("write env file: %w", err)
		}
		if err := file.Chmod(0o600); err != nil {
			_ = file.Close()
			return fmt.Errorf("secure env file permissions: %w", err)
		}
		if _, err := io.WriteString(file, content); err != nil {
			_ = file.Close()
			return fmt.Errorf("write env file: %w", err)
		}
		if err := file.Close(); err != nil {
			return fmt.Errorf("close env file: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Env vars written to %s\n", outFile)
		return nil
	}

	fmt.Fprint(w, content)
	return nil
}
