package main

import (
	"fmt"
	"os"
	"strings"
)

// runConfigExportEnvCmd reads a moltnet.json and prints MOLTNET_* env vars
// in dotenv format. The output is directly usable with init-from-env --env-file.
func runConfigExportEnvCmd(credPath, outFile string, includeGitHubPEM bool) error {
	creds, err := loadCredentials(credPath)
	if err != nil {
		return err
	}
	if creds == nil {
		return fmt.Errorf("no config found at %s", credPath)
	}

	var lines []string
	lines = append(lines, "# Generated by moltnet config export-env")
	lines = append(lines, fmt.Sprintf("MOLTNET_IDENTITY_ID=%s", creds.IdentityID))
	lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_ID=%s", creds.OAuth2.ClientID))
	lines = append(lines, fmt.Sprintf("MOLTNET_CLIENT_SECRET=%s", creds.OAuth2.ClientSecret))
	lines = append(lines, fmt.Sprintf("MOLTNET_PUBLIC_KEY=%s", creds.Keys.PublicKey))
	lines = append(lines, fmt.Sprintf("MOLTNET_PRIVATE_KEY=%s", creds.Keys.PrivateKey))
	lines = append(lines, fmt.Sprintf("MOLTNET_FINGERPRINT=%s", creds.Keys.Fingerprint))
	lines = append(lines, fmt.Sprintf("MOLTNET_API_URL=%s", creds.Endpoints.API))
	if creds.RegisteredAt != "" {
		lines = append(lines, fmt.Sprintf("MOLTNET_REGISTERED_AT=%s", creds.RegisteredAt))
	}

	if creds.GitHub != nil {
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_ID=%s", creds.GitHub.AppID))
		if creds.GitHub.AppSlug != "" {
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_SLUG=%s", creds.GitHub.AppSlug))
		}
		lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_INSTALLATION_ID=%s", creds.GitHub.InstallationID))
		if includeGitHubPEM && creds.GitHub.PrivateKeyPath != "" {
			pem, err := os.ReadFile(creds.GitHub.PrivateKeyPath)
			if err != nil {
				return fmt.Errorf("read GitHub App PEM %q: %w", creds.GitHub.PrivateKeyPath, err)
			}
			// Dotenv multi-line: wrap in double quotes with literal newlines
			lines = append(lines, fmt.Sprintf("MOLTNET_GITHUB_APP_PRIVATE_KEY=%q", strings.TrimSpace(string(pem))))
		}
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")

	if outFile != "" {
		if err := os.WriteFile(outFile, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write env file: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Env vars written to %s\n", outFile)
		return nil
	}

	fmt.Print(content)
	return nil
}
