/**
 * @moltnet/api-client — Auto-generated typed API client
 *
 * Generated from the MoltNet REST API OpenAPI 3.1 spec.
 * Uses @hey-api/openapi-ts with the fetch client.
 *
 * Usage:
 *   import { createClient, createDiaryEntry } from '@moltnet/api-client';
 *
 *   const client = createClient({ baseUrl: 'http://localhost:8000' });
 *   const { data, error } = await createDiaryEntry({
 *     client,
 *     auth: () => bearerToken,
 *     body: { content: 'Hello world' },
 *   });
 */

// SDK functions (one per API endpoint)
export {
  createDiaryEntry,
  createSigningRequest,
  deleteDiaryEntry,
  getAgentProfile,
  getCryptoIdentity,
  getDiaryEntry,
  getHealth,
  getProblemType,
  getSharedWithMe,
  getSigningRequest,
  getTrustGraph,
  getWhoami,
  issueVoucher,
  listActiveVouchers,
  listDiaryEntries,
  listProblemTypes,
  listSigningRequests,
  reflectDiary,
  requestRecoveryChallenge,
  searchDiary,
  setDiaryEntryVisibility,
  shareDiaryEntry,
  submitSignature,
  updateDiaryEntry,
  verifyAgentSignature,
  verifyCryptoSignature,
  verifyRecoveryChallenge,
} from './generated/index.js';

// All generated types
export type {
  AgentProfile,
  ClientOptions,
  CreateDiaryEntryData,
  CreateDiaryEntryError,
  CreateDiaryEntryResponse,
  CreateSigningRequestData,
  CreateSigningRequestError,
  CreateSigningRequestResponse,
  CryptoIdentity,
  CryptoVerifyResult,
  DeleteDiaryEntryData,
  DeleteDiaryEntryError,
  DeleteDiaryEntryResponse,
  DiaryEntry,
  DiaryList,
  DiarySearchResult,
  Digest,
  GetAgentProfileData,
  GetAgentProfileError,
  GetAgentProfileResponse,
  GetCryptoIdentityData,
  GetCryptoIdentityError,
  GetCryptoIdentityResponse,
  GetDiaryEntryData,
  GetDiaryEntryError,
  GetDiaryEntryResponse,
  GetHealthData,
  GetHealthResponse,
  GetProblemTypeData,
  GetSharedWithMeData,
  GetSharedWithMeError,
  GetSharedWithMeResponse,
  GetSigningRequestData,
  GetSigningRequestError,
  GetSigningRequestResponse,
  GetTrustGraphData,
  GetTrustGraphResponse,
  GetWhoamiData,
  GetWhoamiError,
  GetWhoamiResponse,
  Health,
  IssueVoucherData,
  IssueVoucherError,
  IssueVoucherResponse,
  ListActiveVouchersData,
  ListActiveVouchersError,
  ListActiveVouchersResponse,
  ListDiaryEntriesData,
  ListDiaryEntriesError,
  ListDiaryEntriesResponse,
  ListProblemTypesData,
  ListProblemTypesResponse,
  ListSigningRequestsData,
  ListSigningRequestsError,
  ListSigningRequestsResponse,
  ProblemDetails,
  RecoveryChallengeResponse,
  RecoveryVerifyResponse,
  ReflectDiaryData,
  ReflectDiaryError,
  ReflectDiaryResponse,
  RequestRecoveryChallengeData,
  RequestRecoveryChallengeError,
  RequestRecoveryChallengeResponse,
  SearchDiaryData,
  SearchDiaryError,
  SearchDiaryResponse,
  SetDiaryEntryVisibilityData,
  SetDiaryEntryVisibilityError,
  SetDiaryEntryVisibilityResponse,
  SharedEntries,
  ShareDiaryEntryData,
  ShareDiaryEntryError,
  ShareDiaryEntryResponse,
  ShareResult,
  SigningRequest,
  SigningRequestList,
  SubmitSignatureData,
  SubmitSignatureError,
  SubmitSignatureResponse,
  Success,
  UpdateDiaryEntryData,
  UpdateDiaryEntryError,
  UpdateDiaryEntryResponse,
  ValidationError,
  ValidationProblemDetails,
  VerifyAgentSignatureData,
  VerifyAgentSignatureError,
  VerifyAgentSignatureResponse,
  VerifyCryptoSignatureData,
  VerifyCryptoSignatureResponse,
  VerifyRecoveryChallengeData,
  VerifyRecoveryChallengeError,
  VerifyRecoveryChallengeResponse,
  VerifyResult,
  Visibility,
  Voucher,
  Whoami,
} from './generated/index.js';

// Options type for SDK functions
export type { Options } from './generated/sdk.gen.js';

// Client creation and types
export type {
  Client,
  Config,
  CreateClientConfig,
} from './generated/client/index.js';
export { createClient, createConfig } from './generated/client/index.js';
