export {
  assertIdentityAlias,
  deriveMcpUrl,
  getConfigDir,
  getConfigPath,
  getIdentityDir,
  getLegacyConfigPath,
  type GitHubConfig,
  IDENTITY_ALIAS_PATTERN,
  type IdentitySelector,
  type KeysConfig,
  type MoltNetConfig,
  type OAuth2Config,
  readConfig,
  resolveConfigDir,
  type SecretReference,
  updateConfigSection,
  updateGitHubConfig,
  updateKeysConfig,
  updateOAuth2Config,
  writeConfig,
} from './config.js';
export { exportSSHKey } from './ssh.js';
